## Bengaluru House Price Prediction

In [2]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import warnings
warnings.simplefilter('ignore')

In [2]:
df = pd.read_csv("Bengaluru_House_Data.csv")
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [3]:
df.shape

(13320, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [6]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [7]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [8]:
#Check any missing values are present in the data
miss_data=pd.DataFrame({"Missing_values":df.isnull().sum(),'Percentage':(df.isnull().sum()/df.shape[0])*100})
miss_data

              Missing_values  Percentage
area_type                  0    0.000000
availability               0    0.000000
location                   1    0.007508
size                      16    0.120120
society                 5502   41.306306
total_sqft                 0    0.000000
bath                      73    0.548048
balcony                  609    4.572072
price                      0    0.000000

In [9]:
for column in df.columns:
    print(df[column].value_counts())
    print("*" * 20)

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64
********************
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Jul               1
14-Jul               1
16-Nov               1
16-Oct               1
15-Aug               1
Name: availability, Length: 81, dtype: int64
********************
Whitefield             540
Sarjapur  Road         399
Electronic City        302
Kanakpura Road         273
Thanisandra            234
                      ...
Tharabanahalli           1
Sector 4 HSR Layout      1
BEL Layout               1
Navodaya Nagar           1
poornaprajna layout      1
Name: location, Length: 1305, dtype: int64
********************
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 Bedroom       2
11 BHK           2
10 BHK           2
19 BHK           1
14 BHK           1
13 BHK           1
16 BHK           1
43 Bedroom       1
27 BHK           1
18 Bedroom       1
12 Bedroom       1
Name: size, dtype: int64
********************
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
Sohid O     1
Sonet G     1
K ensad     1
VDarmlo     1
Suensda     1
Name: society, Length: 2688, dtype: int64
********************
1200    843
1100    221
1500    205
2400    196
600     180
       ...
2395      1
951       1
2437      1
3125      1
4166      1
Name: total_sqft, Length: 2117, dtype: int64
********************
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
18.0       1
40.0       1
15.0       1
14.0       1
Name: bath, dtype: int64
********************
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: balcony, dtype: int64
********************
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
81.55      1
69.49      1
42.18      1
70.25      1
74.82      1
Name: price, Length: 1994, dtype: int64
********************

In [10]:
df.drop(columns=['area_type', 'availability', 'society', 'balcony'], inplace = True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [13]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [12]:
df['location'].value_counts()

Whitefield             540
Sarjapur  Road         399
Electronic City        302
Kanakpura Road         273
Thanisandra            234
                      ...
Tharabanahalli           1
Sector 4 HSR Layout      1
BEL Layout               1
Navodaya Nagar           1
poornaprajna layout      1
Name: location, Length: 1305, dtype: int64

In [14]:
df['location'] = df['location'].fillna('Sarjapur  Road')

In [15]:
df['size'].value_counts()

2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 Bedroom       2
11 BHK           2
10 BHK           2
19 BHK           1
14 BHK           1
13 BHK           1
16 BHK           1
43 Bedroom       1
27 BHK           1
18 Bedroom       1
12 Bedroom       1
Name: size, dtype: int64

In [16]:
df['size'] = df['size'].fillna('2 BHK')

In [17]:
df['bath'].value_counts()

2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
18.0       1
40.0       1
15.0       1
14.0       1
Name: bath, dtype: int64

In [18]:
df['bath'] = df['bath'].fillna(df['bath'].median())

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [20]:
# here remove the string part of the size and add one more col bhk
df['bhk'] = df['size'].str.split().str.get(0).astype(int)
df['bhk']

0        2
1        4
2        3
3        3
4        2
        ..
13315    5
13316    4
13317    2
13318    4
13319    1
Name: bhk, Length: 13320, dtype: int32

In [21]:
df[df.bhk >20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [22]:
df['total_sqft'].unique()  # see here are some data in range so we have to fix it

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [27]:
def convertRange(x):
    
    temp = x.split('-')
    if len(temp)==2:
        return (float(temp[0]) + float(temp[1]))/2
                
    try:
        return float(x)
                
    except:
        return None

In [28]:
df['total_sqft'] = df['total_sqft'].apply(convertRange)

In [29]:
df.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [30]:
## Price per sq feet

df['price_per_sqft'] = df['price']*100000 / df['total_sqft']

In [31]:
df['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [32]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [33]:
df['location'].value_counts()  # we have to reduce location

Whitefield             540
Sarjapur  Road         400
Electronic City        302
Kanakpura Road         273
Thanisandra            234
                      ...
Tharabanahalli           1
Sector 4 HSR Layout      1
BEL Layout               1
Navodaya Nagar           1
poornaprajna layout      1
Name: location, Length: 1305, dtype: int64

In [34]:
df['location'] = df['location'].apply(lambda x:x.strip())

In [35]:
df['location']

0        Electronic City Phase II
1                Chikka Tirupathi
2                     Uttarahalli
3              Lingadheeranahalli
4                        Kothanur
                   ...
13315                  Whitefield
13316               Richards Town
13317       Raja Rajeshwari Nagar
13318             Padmanabhanagar
13319                Doddathoguru
Name: location, Length: 13320, dtype: object

In [36]:
location_counts = df['location'].value_counts()

In [38]:
location_counts

Whitefield             541
Sarjapur  Road         400
Electronic City        304
Kanakpura Road         273
Thanisandra            237
                      ...
Tharabanahalli           1
Sector 4 HSR Layout      1
BEL Layout               1
Navodaya Nagar           1
Chikkajala               1
Name: location, Length: 1294, dtype: int64

In [40]:
location_counts_less10 = location_counts[location_counts <= 10]
location_counts_less10

1st Block Koramangala    10
Dairy Circle             10
BTM 1st Stage            10
Naganathapura            10
Dodsworth Layout         10
                         ..
Tharabanahalli            1
Sector 4 HSR Layout       1
BEL Layout                1
Navodaya Nagar            1
Chikkajala                1
Name: location, Length: 1053, dtype: int64

In [41]:
df['location'] = df['location'].apply(lambda x:'other' if x in location_counts_less10 else x)

In [45]:
df['location'].value_counts()

other                 2885
Whitefield             541
Sarjapur  Road         400
Electronic City        304
Kanakpura Road         273
                      ...
Marsur                  11
Thyagaraja Nagar        11
HAL 2nd Stage           11
Banjara Layout          11
Pattandur Agrahara      11
Name: location, Length: 242, dtype: int64

In [46]:
df.describe()  # in total sqft mim value is  1 sqft which is not possible

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [47]:
(df['total_sqft']/df['bhk']).describe()

count    13274.000000
mean       575.074878
std        388.205175
min          0.250000
25%        473.333333
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [50]:
df = df[((df['total_sqft']/df['bhk']) >= 300)] # let take area for 1 bhk > 300

In [51]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [52]:
df.shape

(12530, 7)

In [54]:
## see price per sqft has max value 	176470.588235 which is outlier, we have to remove this

def remove_outliers_sqft(df):
    df_output = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        
        st = np.std(subdf.price_per_sqft)
        
        gen_df = subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m + st))]
        df_output = pd.concat([df_output, gen_df], ignore_index = True)
    return df_output

df= remove_outliers_sqft(df)

In [55]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10301.000000  10301.000000  10301.000000  10301.000000    10301.000000
mean    1508.440608      2.471702     91.286372      2.574896     5659.062876
std      880.694214      0.979449     86.342786      0.897649     2265.774749
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.897959
50%     1286.000000      2.000000     67.000000      2.000000     5175.600739
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [59]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
                
            }
            print(location, bhk_stats)
#         for bhk, bhk_df in location_df.groupby('bhk'):
#             stats = bhk_stats.get(bhk-1)
#             if stats and stats['count']>5:
#                 exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft < (stats['mean'])].index.values)
                
    return df.drop(exclude_indices, axis = 'index')

In [60]:
df = bhk_outlier_remover(df)

1st Block Jayanagar {2: {'mean': 11983.805668016194, 'std': 0.0, 'count': 1}}
1st Block Jayanagar {2: {'mean': 11983.805668016194, 'std': 0.0, 'count': 1}, 3: {'mean': 11756.16905248807, 'std': 701.6243657657865, 'count': 3}}
1st Block Jayanagar {2: {'mean': 11983.805668016194, 'std': 0.0, 'count': 1}, 3: {'mean': 11756.16905248807, 'std': 701.6243657657865, 'count': 3}, 4: {'mean': 15018.711280365416, 'std': 1.2278182423353805, 'count': 3}}
1st Phase JP Nagar {1: {'mean': 5952.380952380952, 'std': 0.0, 'count': 1}}
1st Phase JP Nagar {1: {'mean': 5952.380952380952, 'std': 0.0, 'count': 1}, 2: {'mean': 7931.806799837383, 'std': 1534.1422783514054, 'count': 8}}
1st Phase JP Nagar {1: {'mean': 5952.380952380952, 'std': 0.0, 'count': 1}, 2: {'mean': 7931.806799837383, 'std': 1534.1422783514054, 'count': 8}, 3: {'mean': 9151.192151725822, 'std': 1054.731726021645, 'count': 7}}
1st Phase JP Nagar {1: {'mean': 5952.380952380952, 'std': 0.0, 'count': 1}, 2: {'mean': 7931.806799837383, 'std': 1534.1422783514054, 'count': 8}, 3: {'mean': 9151.192151725822, 'std': 1054.731726021645, 'count': 7}, 4: {'mean': 7537.92218148637, 'std': 1607.0591069513537, 'count': 3}}
1st Phase JP Nagar {1: {'mean': 5952.380952380952, 'std': 0.0, 'count': 1}, 2: {'mean': 7931.806799837383, 'std': 1534.1422783514054, 'count': 8}, 3: {'mean': 9151.192151725822, 'std': 1054.731726021645, 'count': 7}, 4: {'mean': 7537.92218148637, 'std': 1607.0591069513537, 'count': 3}, 5: {'mean': 5666.666666666667, 'std': 0.0, 'count': 1}}
2nd Phase Judicial Layout {2: {'mean': 3851.8518518518517, 'std': 497.593660834978, 'count': 3}}
2nd Phase Judicial Layout {2: {'mean': 3851.8518518518517, 'std': 497.593660834978, 'count': 3}, 3: {'mean': 3620.93991671624, 'std': 241.87983343248052, 'count': 5}}
2nd Stage Nagarbhavi {4: {'mean': 15891.203703703704, 'std': 1668.9846920398563, 'count': 4}}
2nd Stage Nagarbhavi {4: {'mean': 15891.203703703704, 'std': 1668.9846920398563, 'count': 4}, 6: {'mean': 16891.666666666668, 'std': 1858.333333333333, 'count': 2}}
5th Block Hbr Layout {2: {'mean': 4755.410708222867, 'std': 374.06419031565235, 'count': 3}}
5th Block Hbr Layout {2: {'mean': 4755.410708222867, 'std': 374.06419031565235, 'count': 3}, 3: {'mean': 5511.811023622047, 'std': 0.0, 'count': 1}}
5th Block Hbr Layout {2: {'mean': 4755.410708222867, 'std': 374.06419031565235, 'count': 3}, 3: {'mean': 5511.811023622047, 'std': 0.0, 'count': 1}, 5: {'mean': 3611.1111111111113, 'std': 0.0, 'count': 1}}
5th Block Hbr Layout {2: {'mean': 4755.410708222867, 'std': 374.06419031565235, 'count': 3}, 3: {'mean': 5511.811023622047, 'std': 0.0, 'count': 1}, 5: {'mean': 3611.1111111111113, 'std': 0.0, 'count': 1}, 6: {'mean': 5882.35294117647, 'std': 0.0, 'count': 1}}
5th Phase JP Nagar {1: {'mean': 4628.623188405797, 'std': 371.376811594203, 'count': 2}}
5th Phase JP Nagar {1: {'mean': 4628.623188405797, 'std': 371.376811594203, 'count': 2}, 2: {'mean': 5067.359785883266, 'std': 453.24956183513086, 'count': 17}}
5th Phase JP Nagar {1: {'mean': 4628.623188405797, 'std': 371.376811594203, 'count': 2}, 2: {'mean': 5067.359785883266, 'std': 453.24956183513086, 'count': 17}, 3: {'mean': 5112.892626961968, 'std': 526.8794907246175, 'count': 8}}
5th Phase JP Nagar {1: {'mean': 4628.623188405797, 'std': 371.376811594203, 'count': 2}, 2: {'mean': 5067.359785883266, 'std': 453.24956183513086, 'count': 17}, 3: {'mean': 5112.892626961968, 'std': 526.8794907246175, 'count': 8}, 5: {'mean': 4325.0, 'std': 75.0, 'count': 2}}
6th Phase JP Nagar {2: {'mean': 5932.976565810136, 'std': 671.9347030151997, 'count': 8}}
6th Phase JP Nagar {2: {'mean': 5932.976565810136, 'std': 671.9347030151997, 'count': 8}, 3: {'mean': 8403.2863080867, 'std': 1515.4146231166221, 'count': 5}}
6th Phase JP Nagar {2: {'mean': 5932.976565810136, 'std': 671.9347030151997, 'count': 8}, 3: {'mean': 8403.2863080867, 'std': 1515.4146231166221, 'count': 5}, 4: {'mean': 7704.160246533128, 'std': 0.0, 'count': 1}}
7th Phase JP Nagar {1: {'mean': 6133.333333333334, 'std': 133.33333333333348, 'count': 2}}
7th Phase JP Nagar {1: {'mean': 6133.333333333334, 'std': 133.33333333333348, 'count': 2}, 2: {'mean': 6272.516842644272, 'std': 1012.7881476778178, 'count': 40}}
7th Phase JP Nagar {1: {'mean': 6133.333333333334, 'std': 133.33333333333348, 'count': 2}, 2: {'mean': 6272.516842644272, 'std': 1012.7881476778178, 'count': 40}, 3: {'mean': 6612.8616825981035, 'std': 1181.6582893458344, 'count': 57}}
7th Phase JP Nagar {1: {'mean': 6133.333333333334, 'std': 133.33333333333348, 'count': 2}, 2: {'mean': 6272.516842644272, 'std': 1012.7881476778178, 'count': 40}, 3: {'mean': 6612.8616825981035, 'std': 1181.6582893458344, 'count': 57}, 4: {'mean': 6028.22068063778, 'std': 1482.7661351832348, 'count': 2}}
8th Phase JP Nagar {1: {'mean': 6357.427937915743, 'std': 267.1694064501245, 'count': 4}}
8th Phase JP Nagar {1: {'mean': 6357.427937915743, 'std': 267.1694064501245, 'count': 4}, 2: {'mean': 4324.406715739656, 'std': 1131.8308808521078, 'count': 22}}
8th Phase JP Nagar {1: {'mean': 6357.427937915743, 'std': 267.1694064501245, 'count': 4}, 2: {'mean': 4324.406715739656, 'std': 1131.8308808521078, 'count': 22}, 3: {'mean': 4293.744876160689, 'std': 723.4267508470377, 'count': 17}}
8th Phase JP Nagar {1: {'mean': 6357.427937915743, 'std': 267.1694064501245, 'count': 4}, 2: {'mean': 4324.406715739656, 'std': 1131.8308808521078, 'count': 22}, 3: {'mean': 4293.744876160689, 'std': 723.4267508470377, 'count': 17}, 4: {'mean': 4539.6147062813725, 'std': 195.35428340140427, 'count': 3}}
8th Phase JP Nagar {1: {'mean': 6357.427937915743, 'std': 267.1694064501245, 'count': 4}, 2: {'mean': 4324.406715739656, 'std': 1131.8308808521078, 'count': 22}, 3: {'mean': 4293.744876160689, 'std': 723.4267508470377, 'count': 17}, 4: {'mean': 4539.6147062813725, 'std': 195.35428340140427, 'count': 3}, 5: {'mean': 4335.260115606937, 'std': 0.0, 'count': 1}}
9th Phase JP Nagar {1: {'mean': 3333.3333333333335, 'std': 0.0, 'count': 1}}
9th Phase JP Nagar {1: {'mean': 3333.3333333333335, 'std': 0.0, 'count': 1}, 2: {'mean': 4653.051383903641, 'std': 834.4408302683472, 'count': 20}}
9th Phase JP Nagar {1: {'mean': 3333.3333333333335, 'std': 0.0, 'count': 1}, 2: {'mean': 4653.051383903641, 'std': 834.4408302683472, 'count': 20}, 3: {'mean': 4518.339436369508, 'std': 790.2476753262926, 'count': 9}}
9th Phase JP Nagar {1: {'mean': 3333.3333333333335, 'std': 0.0, 'count': 1}, 2: {'mean': 4653.051383903641, 'std': 834.4408302683472, 'count': 20}, 3: {'mean': 4518.339436369508, 'std': 790.2476753262926, 'count': 9}, 4: {'mean': 5336.8421052631575, 'std': 800.5999597024291, 'count': 3}}
AECS Layout {2: {'mean': 4921.300339526721, 'std': 619.6355499375203, 'count': 7}}
AECS Layout {2: {'mean': 4921.300339526721, 'std': 619.6355499375203, 'count': 7}, 3: {'mean': 4500.0, 'std': 0.0, 'count': 1}}
Abbigere {1: {'mean': 3310.9205535075066, 'std': 610.6480739434737, 'count': 2}}
Abbigere {1: {'mean': 3310.9205535075066, 'std': 610.6480739434737, 'count': 2}, 2: {'mean': 4058.165803016323, 'std': 62.23518728011486, 'count': 13}}
Abbigere {1: {'mean': 3310.9205535075066, 'std': 610.6480739434737, 'count': 2}, 2: {'mean': 4058.165803016323, 'std': 62.23518728011486, 'count': 13}, 3: {'mean': 3571.4285714285716, 'std': 0.0, 'count': 1}}
Abbigere {1: {'mean': 3310.9205535075066, 'std': 610.6480739434737, 'count': 2}, 2: {'mean': 4058.165803016323, 'std': 62.23518728011486, 'count': 13}, 3: {'mean': 3571.4285714285716, 'std': 0.0, 'count': 1}, 6: {'mean': 3165.4545454545455, 'std': 74.5454545454545, 'count': 2}}
Abbigere {1: {'mean': 3310.9205535075066, 'std': 610.6480739434737, 'count': 2}, 2: {'mean': 4058.165803016323, 'std': 62.23518728011486, 'count': 13}, 3: {'mean': 3571.4285714285716, 'std': 0.0, 'count': 1}, 6: {'mean': 3165.4545454545455, 'std': 74.5454545454545, 'count': 2}, 8: {'mean': 5000.0, 'std': 0.0, 'count': 1}}
Akshaya Nagar {2: {'mean': 4781.22783734999, 'std': 453.10974836521865, 'count': 17}}
Akshaya Nagar {2: {'mean': 4781.22783734999, 'std': 453.10974836521865, 'count': 17}, 3: {'mean': 5294.361032273931, 'std': 513.4396107693667, 'count': 30}}
Ambalipura {1: {'mean': 5690.909090909091, 'std': 0.0, 'count': 1}}
Ambalipura {1: {'mean': 5690.909090909091, 'std': 0.0, 'count': 1}, 2: {'mean': 5886.737386783397, 'std': 736.0640513407117, 'count': 10}}
Ambalipura {1: {'mean': 5690.909090909091, 'std': 0.0, 'count': 1}, 2: {'mean': 5886.737386783397, 'std': 736.0640513407117, 'count': 10}, 3: {'mean': 6331.134555298749, 'std': 569.718562351169, 'count': 7}}
Ambalipura {1: {'mean': 5690.909090909091, 'std': 0.0, 'count': 1}, 2: {'mean': 5886.737386783397, 'std': 736.0640513407117, 'count': 10}, 3: {'mean': 6331.134555298749, 'std': 569.718562351169, 'count': 7}, 4: {'mean': 5503.386809269163, 'std': 339.75044563279835, 'count': 2}}
Ambedkar Nagar {2: {'mean': 6454.091928430547, 'std': 182.0843219299883, 'count': 5}}
Ambedkar Nagar {2: {'mean': 6454.091928430547, 'std': 182.0843219299883, 'count': 5}, 3: {'mean': 6572.746532916982, 'std': 422.13464472691317, 'count': 19}}
Ambedkar Nagar {2: {'mean': 6454.091928430547, 'std': 182.0843219299883, 'count': 5}, 3: {'mean': 6572.746532916982, 'std': 422.13464472691317, 'count': 19}, 4: {'mean': 7684.086312870249, 'std': 531.2111375546801, 'count': 2}}
Amruthahalli {1: {'mean': 4020.618556701031, 'std': 0.0, 'count': 1}}
Amruthahalli {1: {'mean': 4020.618556701031, 'std': 0.0, 'count': 1}, 2: {'mean': 4953.838379629301, 'std': 823.6966143070669, 'count': 12}}
Amruthahalli {1: {'mean': 4020.618556701031, 'std': 0.0, 'count': 1}, 2: {'mean': 4953.838379629301, 'std': 823.6966143070669, 'count': 12}, 3: {'mean': 5574.846418310635, 'std': 1077.4444900329127, 'count': 7}}
Anandapura {2: {'mean': 4335.741837049204, 'std': 710.6695705040866, 'count': 14}}
Anandapura {2: {'mean': 4335.741837049204, 'std': 710.6695705040866, 'count': 14}, 3: {'mean': 4376.900862764794, 'std': 811.4741024839058, 'count': 5}}
Anandapura {2: {'mean': 4335.741837049204, 'std': 710.6695705040866, 'count': 14}, 3: {'mean': 4376.900862764794, 'std': 811.4741024839058, 'count': 5}, 4: {'mean': 5145.797598627787, 'std': 0.0, 'count': 1}}
Ananth Nagar {1: {'mean': 2800.0, 'std': 0.0, 'count': 4}}
Ananth Nagar {1: {'mean': 2800.0, 'std': 0.0, 'count': 4}, 2: {'mean': 3015.424249737158, 'std': 491.5389870277813, 'count': 19}}
Ananth Nagar {1: {'mean': 2800.0, 'std': 0.0, 'count': 4}, 2: {'mean': 3015.424249737158, 'std': 491.5389870277813, 'count': 19}, 3: {'mean': 3239.9055148973916, 'std': 333.6052126335633, 'count': 3}}
Anekal {1: {'mean': 3307.549188983317, 'std': 602.8526665064047, 'count': 6}}
Anekal {1: {'mean': 3307.549188983317, 'std': 602.8526665064047, 'count': 6}, 2: {'mean': 3418.531131818201, 'std': 543.1514964904059, 'count': 22}}
Anekal {1: {'mean': 3307.549188983317, 'std': 602.8526665064047, 'count': 6}, 2: {'mean': 3418.531131818201, 'std': 543.1514964904059, 'count': 22}, 3: {'mean': 4075.680581158921, 'std': 340.19143395777115, 'count': 4}}
Anekal {1: {'mean': 3307.549188983317, 'std': 602.8526665064047, 'count': 6}, 2: {'mean': 3418.531131818201, 'std': 543.1514964904059, 'count': 22}, 3: {'mean': 4075.680581158921, 'std': 340.19143395777115, 'count': 4}, 4: {'mean': 3000.0, 'std': 0.0, 'count': 1}}
Anjanapura {2: {'mean': 3451.5654968214635, 'std': 402.7964034804156, 'count': 7}}
Anjanapura {2: {'mean': 3451.5654968214635, 'std': 402.7964034804156, 'count': 7}, 3: {'mean': 4783.11324361657, 'std': 2019.9576386770505, 'count': 4}}
Anjanapura {2: {'mean': 3451.5654968214635, 'std': 402.7964034804156, 'count': 7}, 3: {'mean': 4783.11324361657, 'std': 2019.9576386770505, 'count': 4}, 4: {'mean': 3852.102102102102, 'std': 796.5465465465463, 'count': 2}}
Ardendale {2: {'mean': 5596.405228758171, 'std': 122.54901960784309, 'count': 2}}
Ardendale {2: {'mean': 5596.405228758171, 'std': 122.54901960784309, 'count': 2}, 3: {'mean': 5378.184432045396, 'std': 324.88136834734956, 'count': 10}}
Ardendale {2: {'mean': 5596.405228758171, 'std': 122.54901960784309, 'count': 2}, 3: {'mean': 5378.184432045396, 'std': 324.88136834734956, 'count': 10}, 4: {'mean': 6445.687085352693, 'std': 663.0498079730814, 'count': 7}}
Arekere {1: {'mean': 4666.666666666667, 'std': 0.0, 'count': 1}}
Arekere {1: {'mean': 4666.666666666667, 'std': 0.0, 'count': 1}, 2: {'mean': 4884.730750645279, 'std': 371.1132245946985, 'count': 6}}
Arekere {1: {'mean': 4666.666666666667, 'std': 0.0, 'count': 1}, 2: {'mean': 4884.730750645279, 'std': 371.1132245946985, 'count': 6}, 3: {'mean': 5822.747277384037, 'std': 695.6480303741811, 'count': 3}}
Arekere {1: {'mean': 4666.666666666667, 'std': 0.0, 'count': 1}, 2: {'mean': 4884.730750645279, 'std': 371.1132245946985, 'count': 6}, 3: {'mean': 5822.747277384037, 'std': 695.6480303741811, 'count': 3}, 4: {'mean': 5239.852398523985, 'std': 0.0, 'count': 1}}
Attibele {1: {'mean': 2823.051298353896, 'std': 440.885126183788, 'count': 18}}
Attibele {1: {'mean': 2823.051298353896, 'std': 440.885126183788, 'count': 18}, 2: {'mean': 3204.1609520225243, 'std': 617.2070386969107, 'count': 12}}
Attibele {1: {'mean': 2823.051298353896, 'std': 440.885126183788, 'count': 18}, 2: {'mean': 3204.1609520225243, 'std': 617.2070386969107, 'count': 12}, 3: {'mean': 4330.95861895704, 'std': 1307.8696742735906, 'count': 4}}
Attibele {1: {'mean': 2823.051298353896, 'std': 440.885126183788, 'count': 18}, 2: {'mean': 3204.1609520225243, 'std': 617.2070386969107, 'count': 12}, 3: {'mean': 4330.95861895704, 'std': 1307.8696742735906, 'count': 4}, 4: {'mean': 3840.959409594096, 'std': 540.9594095940961, 'count': 2}}
BEML Layout {2: {'mean': 5944.048212904286, 'std': 1628.8084083258766, 'count': 6}}
BEML Layout {2: {'mean': 5944.048212904286, 'std': 1628.8084083258766, 'count': 6}, 3: {'mean': 4250.0, 'std': 0.0, 'count': 4}}
BEML Layout {2: {'mean': 5944.048212904286, 'std': 1628.8084083258766, 'count': 6}, 3: {'mean': 4250.0, 'std': 0.0, 'count': 4}, 5: {'mean': 9375.0, 'std': 0.0, 'count': 1}}
BTM 2nd Stage {2: {'mean': 5621.791028153005, 'std': 795.7682556051348, 'count': 14}}
BTM 2nd Stage {2: {'mean': 5621.791028153005, 'std': 795.7682556051348, 'count': 14}, 3: {'mean': 10282.085985474581, 'std': 3831.770494859885, 'count': 9}}
BTM 2nd Stage {2: {'mean': 5621.791028153005, 'std': 795.7682556051348, 'count': 14}, 3: {'mean': 10282.085985474581, 'std': 3831.770494859885, 'count': 9}, 5: {'mean': 13913.04347826087, 'std': 0.0, 'count': 1}}
BTM Layout {1: {'mean': 4444.444444444444, 'std': 0.0, 'count': 1}}
BTM Layout {1: {'mean': 4444.444444444444, 'std': 0.0, 'count': 1}, 2: {'mean': 5073.776447337828, 'std': 424.90705275056126, 'count': 4}}
BTM Layout {1: {'mean': 4444.444444444444, 'std': 0.0, 'count': 1}, 2: {'mean': 5073.776447337828, 'std': 424.90705275056126, 'count': 4}, 3: {'mean': 5685.2029893641175, 'std': 881.6401846985812, 'count': 7}}
BTM Layout {1: {'mean': 4444.444444444444, 'std': 0.0, 'count': 1}, 2: {'mean': 5073.776447337828, 'std': 424.90705275056126, 'count': 4}, 3: {'mean': 5685.2029893641175, 'std': 881.6401846985812, 'count': 7}, 6: {'mean': 5000.0, 'std': 0.0, 'count': 1}}
Babusapalaya {2: {'mean': 3799.9594889549185, 'std': 423.8304869618115, 'count': 11}}
Babusapalaya {2: {'mean': 3799.9594889549185, 'std': 423.8304869618115, 'count': 11}, 3: {'mean': 3669.941030877054, 'std': 601.932707346431, 'count': 10}}
Badavala Nagar {2: {'mean': 6357.9277864992155, 'std': 0.0, 'count': 2}}
Badavala Nagar {2: {'mean': 6357.9277864992155, 'std': 0.0, 'count': 2}, 3: {'mean': 6279.828480978357, 'std': 42.27887875035828, 'count': 7}}
Balagere {1: {'mean': 5865.01000449379, 'std': 539.315075028032, 'count': 9}}
Balagere {1: {'mean': 5865.01000449379, 'std': 539.315075028032, 'count': 9}, 2: {'mean': 6191.4951431862855, 'std': 543.3822583816924, 'count': 28}}
Banashankari {1: {'mean': 8333.333333333334, 'std': 0.0, 'count': 2}}
Banashankari {1: {'mean': 8333.333333333334, 'std': 0.0, 'count': 2}, 2: {'mean': 5038.253269278572, 'std': 1168.5163463486565, 'count': 31}}
Banashankari {1: {'mean': 8333.333333333334, 'std': 0.0, 'count': 2}, 2: {'mean': 5038.253269278572, 'std': 1168.5163463486565, 'count': 31}, 3: {'mean': 5817.282245183153, 'std': 1663.833391137828, 'count': 29}}
Banashankari {1: {'mean': 8333.333333333334, 'std': 0.0, 'count': 2}, 2: {'mean': 5038.253269278572, 'std': 1168.5163463486565, 'count': 31}, 3: {'mean': 5817.282245183153, 'std': 1663.833391137828, 'count': 29}, 4: {'mean': 3800.0, 'std': 0.0, 'count': 1}}

Banashankari Stage II {2: {'mean': 8701.636799298034, 'std': 1030.287972433991, 'count': 4}}
Banashankari Stage II {2: {'mean': 8701.636799298034, 'std': 1030.287972433991, 'count': 4}, 3: {'mean': 10723.280423280425, 'std': 4231.90962768462, 'count': 6}}
Banashankari Stage II {2: {'mean': 8701.636799298034, 'std': 1030.287972433991, 'count': 4}, 3: {'mean': 10723.280423280425, 'std': 4231.90962768462, 'count': 6}, 4: {'mean': 12500.0, 'std': 0.0, 'count': 1}}
Banashankari Stage II {2: {'mean': 8701.636799298034, 'std': 1030.287972433991, 'count': 4}, 3: {'mean': 10723.280423280425, 'std': 4231.90962768462, 'count': 6}, 4: {'mean': 12500.0, 'std': 0.0, 'count': 1}, 5: {'mean': 18214.285714285714, 'std': 3035.7142857142853, 'count': 2}}
Banashankari Stage III {2: {'mean': 5430.250387687147, 'std': 1871.4365421808766, 'count': 4}}
Banashankari Stage III {2: {'mean': 5430.250387687147, 'std': 1871.4365421808766, 'count': 4}, 3: {'mean': 5330.43635317069, 'std': 1014.1370099612311, 'count': 10}}
Banashankari Stage III {2: {'mean': 5430.250387687147, 'std': 1871.4365421808766, 'count': 4}, 3: {'mean': 5330.43635317069, 'std': 1014.1370099612311, 'count': 10}, 4: {'mean': 7333.333333333333, 'std': 2054.8046676563254, 'count': 3}}
Banashankari Stage III {2: {'mean': 5430.250387687147, 'std': 1871.4365421808766, 'count': 4}, 3: {'mean': 5330.43635317069, 'std': 1014.1370099612311, 'count': 10}, 4: {'mean': 7333.333333333333, 'std': 2054.8046676563254, 'count': 3}, 6: {'mean': 5000.0, 'std': 0.0, 'count': 1}}
Banashankari Stage V {2: {'mean': 3983.4541062801936, 'std': 527.4154589371976, 'count': 2}}
Banashankari Stage V {2: {'mean': 3983.4541062801936, 'std': 527.4154589371976, 'count': 2}, 3: {'mean': 3581.5713402611805, 'std': 544.8260330690271, 'count': 9}}
Banashankari Stage VI {2: {'mean': 5072.0195454829345, 'std': 22.81429179660186, 'count': 3}}
Banashankari Stage VI {2: {'mean': 5072.0195454829345, 'std': 22.81429179660186, 'count': 3}, 3: {'mean': 5006.925310122253, 'std': 23.924063833179062, 'count': 3}}
Banashankari Stage VI {2: {'mean': 5072.0195454829345, 'std': 22.81429179660186, 'count': 3}, 3: {'mean': 5006.925310122253, 'std': 23.924063833179062, 'count': 3}, 4: {'mean': 5041.801948051948, 'std': 2237.063491984229, 'count': 4}}
Banaswadi {1: {'mean': 6641.366223908918, 'std': 0.0, 'count': 1}}
Banaswadi {1: {'mean': 6641.366223908918, 'std': 0.0, 'count': 1}, 2: {'mean': 5110.715347907356, 'std': 582.5694084547944, 'count': 10}}
Banaswadi {1: {'mean': 6641.366223908918, 'std': 0.0, 'count': 1}, 2: {'mean': 5110.715347907356, 'std': 582.5694084547944, 'count': 10}, 3: {'mean': 4656.25, 'std': 0.0, 'count': 1}}
Banaswadi {1: {'mean': 6641.366223908918, 'std': 0.0, 'count': 1}, 2: {'mean': 5110.715347907356, 'std': 582.5694084547944, 'count': 10}, 3: {'mean': 4656.25, 'std': 0.0, 'count': 1}, 5: {'mean': 7356.8050446663165, 'std': 0.0, 'count': 1}}
Banjara Layout {2: {'mean': 6635.496110794916, 'std': 905.9365352849989, 'count': 3}}
Banjara Layout {2: {'mean': 6635.496110794916, 'std': 905.9365352849989, 'count': 3}, 3: {'mean': 5600.0, 'std': 0.0, 'count': 1}}
Bannerghatta {2: {'mean': 6630.037324398989, 'std': 872.6962508901346, 'count': 4}}
Bannerghatta {2: {'mean': 6630.037324398989, 'std': 872.6962508901346, 'count': 4}, 3: {'mean': 7565.595658950089, 'std': 786.4254337865935, 'count': 4}}
Bannerghatta {2: {'mean': 6630.037324398989, 'std': 872.6962508901346, 'count': 4}, 3: {'mean': 7565.595658950089, 'std': 786.4254337865935, 'count': 4}, 4: {'mean': 8398.03739052883, 'std': 97.90458840399697, 'count': 2}}
Bannerghatta Road {1: {'mean': 4932.455648926237, 'std': 741.987966876004, 'count': 5}}
Bannerghatta Road {1: {'mean': 4932.455648926237, 'std': 741.987966876004, 'count': 5}, 2: {'mean': 5156.7223242312, 'std': 951.8519337869209, 'count': 59}}
Bannerghatta Road {1: {'mean': 4932.455648926237, 'std': 741.987966876004, 'count': 5}, 2: {'mean': 5156.7223242312, 'std': 951.8519337869209, 'count': 59}, 3: {'mean': 5384.498056381959, 'std': 1219.6689012468119, 'count': 71}}
Bannerghatta Road {1: {'mean': 4932.455648926237, 'std': 741.987966876004, 'count': 5}, 2: {'mean': 5156.7223242312, 'std': 951.8519337869209, 'count': 59}, 3: {'mean': 5384.498056381959, 'std': 1219.6689012468119, 'count': 71}, 4: {'mean': 5968.786895986739, 'std': 1737.4673135012401, 'count': 8}}
Bannerghatta Road {1: {'mean': 4932.455648926237, 'std': 741.987966876004, 'count': 5}, 2: {'mean': 5156.7223242312, 'std': 951.8519337869209, 'count': 59}, 3: {'mean': 5384.498056381959, 'std': 1219.6689012468119, 'count': 71}, 4: {'mean': 5968.786895986739, 'std': 1737.4673135012401, 'count': 8}, 5: {'mean': 5851.851851851852, 'std': 0.0, 'count': 1}}
Bannerghatta Road {1: {'mean': 4932.455648926237, 'std': 741.987966876004, 'count': 5}, 2: {'mean': 5156.7223242312, 'std': 951.8519337869209, 'count': 59}, 3: {'mean': 5384.498056381959, 'std': 1219.6689012468119, 'count': 71}, 4: {'mean': 5968.786895986739, 'std': 1737.4673135012401, 'count': 8}, 5: {'mean': 5851.851851851852, 'std': 0.0, 'count': 1}, 6: {'mean': 8108.108108108108, 'std': 0.0, 'count': 1}}
Basavangudi {2: {'mean': 9700.42512839123, 'std': 665.8646001174526, 'count': 6}}
Basavangudi {2: {'mean': 9700.42512839123, 'std': 665.8646001174526, 'count': 6}, 3: {'mean': 9210.853069429275, 'std': 904.4272935920624, 'count': 10}}
Basavangudi {2: {'mean': 9700.42512839123, 'std': 665.8646001174526, 'count': 6}, 3: {'mean': 9210.853069429275, 'std': 904.4272935920624, 'count': 10}, 4: {'mean': 10095.80105992662, 'std': 95.80105992662084, 'count': 2}}
Basaveshwara Nagar {2: {'mean': 6750.0, 'std': 552.7707983925667, 'count': 5}}
Basaveshwara Nagar {2: {'mean': 6750.0, 'std': 552.7707983925667, 'count': 5}, 3: {'mean': 7834.767884859602, 'std': 59.968957245661386, 'count': 2}}
Basaveshwara Nagar {2: {'mean': 6750.0, 'std': 552.7707983925667, 'count': 5}, 3: {'mean': 7834.767884859602, 'std': 59.968957245661386, 'count': 2}, 5: {'mean': 11069.444444444445, 'std': 1847.2222222222217, 'count': 2}}
Battarahalli {2: {'mean': 4345.724306884857, 'std': 823.6340914029164, 'count': 9}}
Battarahalli {2: {'mean': 4345.724306884857, 'std': 823.6340914029164, 'count': 9}, 3: {'mean': 5015.40017552159, 'std': 337.7428143761158, 'count': 8}}
Begur {2: {'mean': 4961.668185533498, 'std': 39.10751993914706, 'count': 3}}
Begur {2: {'mean': 4961.668185533498, 'std': 39.10751993914706, 'count': 3}, 3: {'mean': 4510.654979278204, 'std': 599.1143016556773, 'count': 9}}
Begur {2: {'mean': 4961.668185533498, 'std': 39.10751993914706, 'count': 3}, 3: {'mean': 4510.654979278204, 'std': 599.1143016556773, 'count': 9}, 4: {'mean': 3906.25, 'std': 0.0, 'count': 1}}
Begur Road {2: {'mean': 3624.166282880881, 'std': 262.3730178311292, 'count': 35}}
Begur Road {2: {'mean': 3624.166282880881, 'std': 262.3730178311292, 'count': 35}, 3: {'mean': 3684.8720181009567, 'std': 378.82522322146735, 'count': 28}}
Begur Road {2: {'mean': 3624.166282880881, 'std': 262.3730178311292, 'count': 35}, 3: {'mean': 3684.8720181009567, 'std': 378.82522322146735, 'count': 28}, 4: {'mean': 4787.9894501927365, 'std': 0.0, 'count': 1}}
Bellandur {1: {'mean': 4210.526315789473, 'std': 0.0, 'count': 1}}
Bellandur {1: {'mean': 4210.526315789473, 'std': 0.0, 'count': 1}, 2: {'mean': 5116.644099551324, 'std': 1016.3979870126873, 'count': 52}}
Bellandur {1: {'mean': 4210.526315789473, 'std': 0.0, 'count': 1}, 2: {'mean': 5116.644099551324, 'std': 1016.3979870126873, 'count': 52}, 3: {'mean': 5647.571810653258, 'std': 1127.9673046785176, 'count': 31}}
Bellandur {1: {'mean': 4210.526315789473, 'std': 0.0, 'count': 1}, 2: {'mean': 5116.644099551324, 'std': 1016.3979870126873, 'count': 52}, 3: {'mean': 5647.571810653258, 'std': 1127.9673046785176, 'count': 31}, 4: {'mean': 6759.122130530177, 'std': 845.9579630611066, 'count': 4}}
Benson Town {2: {'mean': 12686.709975197631, 'std': 3611.8164390019756, 'count': 4}}
Benson Town {2: {'mean': 12686.709975197631, 'std': 3611.8164390019756, 'count': 4}, 3: {'mean': 14313.731148045554, 'std': 2420.56421489562, 'count': 3}}
Benson Town {2: {'mean': 12686.709975197631, 'std': 3611.8164390019756, 'count': 4}, 3: {'mean': 14313.731148045554, 'std': 2420.56421489562, 'count': 3}, 4: {'mean': 14856.497304850036, 'std': 282.5062734599014, 'count': 2}}
Bharathi Nagar {2: {'mean': 4813.740209190312, 'std': 471.43026983759114, 'count': 8}}
Bharathi Nagar {2: {'mean': 4813.740209190312, 'std': 471.43026983759114, 'count': 8}, 3: {'mean': 4200.120192307692, 'std': 0.0, 'count': 1}}
Bhoganhalli {2: {'mean': 5417.416718889453, 'std': 285.36806332317167, 'count': 12}}
Bhoganhalli {2: {'mean': 5417.416718889453, 'std': 285.36806332317167, 'count': 12}, 3: {'mean': 6125.4200445093, 'std': 899.1112373435706, 'count': 13}}
Bhoganhalli {2: {'mean': 5417.416718889453, 'std': 285.36806332317167, 'count': 12}, 3: {'mean': 6125.4200445093, 'std': 899.1112373435706, 'count': 13}, 4: {'mean': 5777.756745789307, 'std': 871.3161320532748, 'count': 11}}
Billekahalli {2: {'mean': 5962.1264143650205, 'std': 952.8379048046246, 'count': 7}}
Billekahalli {2: {'mean': 5962.1264143650205, 'std': 952.8379048046246, 'count': 7}, 3: {'mean': 6179.829109009818, 'std': 1029.8742088847782, 'count': 6}}
Binny Pete {1: {'mean': 8034.164957849169, 'std': 901.878395083154, 'count': 4}}
Binny Pete {1: {'mean': 8034.164957849169, 'std': 901.878395083154, 'count': 4}, 2: {'mean': 7933.924709828325, 'std': 1003.8042279006136, 'count': 2}}
Binny Pete {1: {'mean': 8034.164957849169, 'std': 901.878395083154, 'count': 4}, 2: {'mean': 7933.924709828325, 'std': 1003.8042279006136, 'count': 2}, 3: {'mean': 8471.722137179819, 'std': 951.1093605219069, 'count': 6}}
Binny Pete {1: {'mean': 8034.164957849169, 'std': 901.878395083154, 'count': 4}, 2: {'mean': 7933.924709828325, 'std': 1003.8042279006136, 'count': 2}, 3: {'mean': 8471.722137179819, 'std': 951.1093605219069, 'count': 6}, 4: {'mean': 8382.135462880804, 'std': 1141.674060928719, 'count': 2}}
Bisuvanahalli {2: {'mean': 3863.8012733035357, 'std': 405.2872025065846, 'count': 12}}
Bisuvanahalli {2: {'mean': 3863.8012733035357, 'std': 405.2872025065846, 'count': 12}, 3: {'mean': 4006.582535464375, 'std': 468.023038908377, 'count': 31}}
Bommanahalli {1: {'mean': 4302.184466019417, 'std': 552.1844660194174, 'count': 2}}
Bommanahalli {1: {'mean': 4302.184466019417, 'std': 552.1844660194174, 'count': 2}, 2: {'mean': 4544.41960101665, 'std': 569.7400942075514, 'count': 9}}
Bommanahalli {1: {'mean': 4302.184466019417, 'std': 552.1844660194174, 'count': 2}, 2: {'mean': 4544.41960101665, 'std': 569.7400942075514, 'count': 9}, 3: {'mean': 4254.328104328105, 'std': 505.922183603648, 'count': 4}}
Bommanahalli {1: {'mean': 4302.184466019417, 'std': 552.1844660194174, 'count': 2}, 2: {'mean': 4544.41960101665, 'std': 569.7400942075514, 'count': 9}, 3: {'mean': 4254.328104328105, 'std': 505.922183603648, 'count': 4}, 4: {'mean': 4047.6190476190477, 'std': 0.0, 'count': 1}}
Bommanahalli {1: {'mean': 4302.184466019417, 'std': 552.1844660194174, 'count': 2}, 2: {'mean': 4544.41960101665, 'std': 569.7400942075514, 'count': 9}, 3: {'mean': 4254.328104328105, 'std': 505.922183603648, 'count': 4}, 4: {'mean': 4047.6190476190477, 'std': 0.0, 'count': 1}, 8: {'mean': 4666.666666666667, 'std': 0.0, 'count': 1}}
Bommasandra {2: {'mean': 3813.947572153106, 'std': 244.23665886444502, 'count': 19}}
Bommasandra {2: {'mean': 3813.947572153106, 'std': 244.23665886444502, 'count': 19}, 3: {'mean': 3815.8530659565145, 'std': 403.8116627539011, 'count': 11}}
Bommasandra Industrial Area {2: {'mean': 2887.892987573868, 'std': 0.47920744469383775, 'count': 11}}
Bommasandra Industrial Area {2: {'mean': 2887.892987573868, 'std': 0.47920744469383775, 'count': 11}, 3: {'mean': 2863.160206574431, 'std': 59.9654742104211, 'count': 7}}
Bommenahalli {3: {'mean': 8565.382032363164, 'std': 1314.9620051314946, 'count': 3}}
Bommenahalli {3: {'mean': 8565.382032363164, 'std': 1314.9620051314946, 'count': 3}, 4: {'mean': 8564.836466843257, 'std': 717.6221010374835, 'count': 6}}
Brookefield {2: {'mean': 5837.4926933902225, 'std': 903.6255944977522, 'count': 19}}
Brookefield {2: {'mean': 5837.4926933902225, 'std': 903.6255944977522, 'count': 19}, 3: {'mean': 5795.407173862258, 'std': 1201.0625471599164, 'count': 13}}
Brookefield {2: {'mean': 5837.4926933902225, 'std': 903.6255944977522, 'count': 19}, 3: {'mean': 5795.407173862258, 'std': 1201.0625471599164, 'count': 13}, 4: {'mean': 6680.252598242926, 'std': 2089.3417875296827, 'count': 7}}
Brookefield {2: {'mean': 5837.4926933902225, 'std': 903.6255944977522, 'count': 19}, 3: {'mean': 5795.407173862258, 'std': 1201.0625471599164, 'count': 13}, 4: {'mean': 6680.252598242926, 'std': 2089.3417875296827, 'count': 7}, 5: {'mean': 8974.358974358975, 'std': 0.0, 'count': 1}}
Budigere {1: {'mean': 5155.722891566265, 'std': 166.41859289793305, 'count': 4}}
Budigere {1: {'mean': 5155.722891566265, 'std': 166.41859289793305, 'count': 4}, 2: {'mean': 5034.160717791255, 'std': 199.14597741069483, 'count': 23}}
Budigere {1: {'mean': 5155.722891566265, 'std': 166.41859289793305, 'count': 4}, 2: {'mean': 5034.160717791255, 'std': 199.14597741069483, 'count': 23}, 3: {'mean': 4995.78214595029, 'std': 304.7321376982579, 'count': 22}}
CV Raman Nagar {1: {'mean': 7092.198581560284, 'std': 0.0, 'count': 1}}
CV Raman Nagar {1: {'mean': 7092.198581560284, 'std': 0.0, 'count': 1}, 2: {'mean': 5155.724160108177, 'std': 750.6157631590067, 'count': 18}}
CV Raman Nagar {1: {'mean': 7092.198581560284, 'std': 0.0, 'count': 1}, 2: {'mean': 5155.724160108177, 'std': 750.6157631590067, 'count': 18}, 3: {'mean': 5069.118281564101, 'std': 895.7302193450796, 'count': 8}}
Chamrajpet {1: {'mean': 16831.68316831683, 'std': 0.0, 'count': 1}}
Chamrajpet {1: {'mean': 16831.68316831683, 'std': 0.0, 'count': 1}, 2: {'mean': 9792.423102012144, 'std': 3818.3998448404645, 'count': 5}}
Chamrajpet {1: {'mean': 16831.68316831683, 'std': 0.0, 'count': 1}, 2: {'mean': 9792.423102012144, 'std': 3818.3998448404645, 'count': 5}, 3: {'mean': 7141.805995187703, 'std': 751.0857983228121, 'count': 3}}
Chamrajpet {1: {'mean': 16831.68316831683, 'std': 0.0, 'count': 1}, 2: {'mean': 9792.423102012144, 'std': 3818.3998448404645, 'count': 5}, 3: {'mean': 7141.805995187703, 'std': 751.0857983228121, 'count': 3}, 4: {'mean': 10827.574839290468, 'std': 1880.2064182378372, 'count': 2}}
Chandapura {1: {'mean': 2520.6090114704184, 'std': 140.15700556082749, 'count': 19}}
Chandapura {1: {'mean': 2520.6090114704184, 'std': 140.15700556082749, 'count': 19}, 2: {'mean': 2822.693874744619, 'std': 410.55761448180084, 'count': 37}}
Chandapura {1: {'mean': 2520.6090114704184, 'std': 140.15700556082749, 'count': 19}, 2: {'mean': 2822.693874744619, 'std': 410.55761448180084, 'count': 37}, 3: {'mean': 2853.1236984866746, 'std': 427.6538083676819, 'count': 26}}
Chandapura {1: {'mean': 2520.6090114704184, 'std': 140.15700556082749, 'count': 19}, 2: {'mean': 2822.693874744619, 'std': 410.55761448180084, 'count': 37}, 3: {'mean': 2853.1236984866746, 'std': 427.6538083676819, 'count': 26}, 4: {'mean': 3498.942358540455, 'std': 0.0, 'count': 1}}
Channasandra {2: {'mean': 3613.5088756107502, 'std': 502.5086800433043, 'count': 24}}
Channasandra {2: {'mean': 3613.5088756107502, 'std': 502.5086800433043, 'count': 24}, 3: {'mean': 4500.644242719408, 'std': 1005.213241509808, 'count': 9}}
Channasandra {2: {'mean': 3613.5088756107502, 'std': 502.5086800433043, 'count': 24}, 3: {'mean': 4500.644242719408, 'std': 1005.213241509808, 'count': 9}, 4: {'mean': 5963.333333333333, 'std': 0.0, 'count': 1}}
Channasandra {2: {'mean': 3613.5088756107502, 'std': 502.5086800433043, 'count': 24}, 3: {'mean': 4500.644242719408, 'std': 1005.213241509808, 'count': 9}, 4: {'mean': 5963.333333333333, 'std': 0.0, 'count': 1}, 6: {'mean': 4285.714285714285, 'std': 0.0, 'count': 1}}
Chikka Tirupathi {3: {'mean': 4090.4654941407116, 'std': 246.87536752515462, 'count': 4}}
Chikka Tirupathi {3: {'mean': 4090.4654941407116, 'std': 246.87536752515462, 'count': 4}, 4: {'mean': 4568.837506464278, 'std': 449.90860011916783, 'count': 7}}

Chikkabanavar {2: {'mean': 3979.526682999282, 'std': 296.21104114438486, 'count': 3}}
Chikkabanavar {2: {'mean': 3979.526682999282, 'std': 296.21104114438486, 'count': 3}, 3: {'mean': 4242.424242424242, 'std': 757.5757575757575, 'count': 2}}
Chikkabanavar {2: {'mean': 3979.526682999282, 'std': 296.21104114438486, 'count': 3}, 3: {'mean': 4242.424242424242, 'std': 757.5757575757575, 'count': 2}, 4: {'mean': 3252.032520325203, 'std': 0.0, 'count': 1}}
Chikkabanavar {2: {'mean': 3979.526682999282, 'std': 296.21104114438486, 'count': 3}, 3: {'mean': 4242.424242424242, 'std': 757.5757575757575, 'count': 2}, 4: {'mean': 3252.032520325203, 'std': 0.0, 'count': 1}, 5: {'mean': 3645.833333333333, 'std': 395.83333333333326, 'count': 2}}
Chikkabanavar {2: {'mean': 3979.526682999282, 'std': 296.21104114438486, 'count': 3}, 3: {'mean': 4242.424242424242, 'std': 757.5757575757575, 'count': 2}, 4: {'mean': 3252.032520325203, 'std': 0.0, 'count': 1}, 5: {'mean': 3645.833333333333, 'std': 395.83333333333326, 'count': 2}, 8: {'mean': 2750.0, 'std': 0.0, 'count': 1}}
Chikkalasandra {2: {'mean': 4680.6659357581775, 'std': 906.7207027292567, 'count': 14}}
Chikkalasandra {2: {'mean': 4680.6659357581775, 'std': 906.7207027292567, 'count': 14}, 3: {'mean': 4209.541795721919, 'std': 468.54274526277595, 'count': 14}}
Choodasandra {2: {'mean': 4782.163531612381, 'std': 528.754856051744, 'count': 12}}
Choodasandra {2: {'mean': 4782.163531612381, 'std': 528.754856051744, 'count': 12}, 3: {'mean': 4993.1936034011, 'std': 599.6867241072546, 'count': 10}}
Choodasandra {2: {'mean': 4782.163531612381, 'std': 528.754856051744, 'count': 12}, 3: {'mean': 4993.1936034011, 'std': 599.6867241072546, 'count': 10}, 4: {'mean': 8645.533141210375, 'std': 0.0, 'count': 1}}
Cooke Town {2: {'mean': 9450.335685771604, 'std': 1592.310446826406, 'count': 3}}
Cooke Town {2: {'mean': 9450.335685771604, 'std': 1592.310446826406, 'count': 3}, 3: {'mean': 11852.598087462115, 'std': 1661.385526814624, 'count': 4}}
Cooke Town {2: {'mean': 9450.335685771604, 'std': 1592.310446826406, 'count': 3}, 3: {'mean': 11852.598087462115, 'std': 1661.385526814624, 'count': 4}, 4: {'mean': 11016.71535215839, 'std': 375.6897111327489, 'count': 2}}
Cox Town {2: {'mean': 8230.365020192607, 'std': 2084.870283562963, 'count': 5}}
Cox Town {2: {'mean': 8230.365020192607, 'std': 2084.870283562963, 'count': 5}, 3: {'mean': 7780.757079649942, 'std': 1186.6163940265649, 'count': 4}}
Cunningham Road {3: {'mean': 19562.04239043375, 'std': 1371.647354515775, 'count': 8}}
Cunningham Road {3: {'mean': 19562.04239043375, 'std': 1371.647354515775, 'count': 8}, 4: {'mean': 22399.47110781565, 'std': 2068.0898222124456, 'count': 3}}
Dasanapura {1: {'mean': 5790.960451977401, 'std': 0.0, 'count': 1}}
Dasanapura {1: {'mean': 5790.960451977401, 'std': 0.0, 'count': 1}, 2: {'mean': 5113.831187981814, 'std': 479.0067310357899, 'count': 7}}
Dasanapura {1: {'mean': 5790.960451977401, 'std': 0.0, 'count': 1}, 2: {'mean': 5113.831187981814, 'std': 479.0067310357899, 'count': 7}, 3: {'mean': 5032.659409020218, 'std': 255.05443234836684, 'count': 2}}
Dasarahalli {2: {'mean': 5117.938928017428, 'std': 689.5131286166418, 'count': 6}}
Dasarahalli {2: {'mean': 5117.938928017428, 'std': 689.5131286166418, 'count': 6}, 3: {'mean': 5324.248120300752, 'std': 390.03759398496277, 'count': 2}}
Devanahalli {1: {'mean': 4606.9148770709035, 'std': 456.2054151733658, 'count': 7}}
Devanahalli {1: {'mean': 4606.9148770709035, 'std': 456.2054151733658, 'count': 7}, 2: {'mean': 4936.153738448984, 'std': 478.78750862962505, 'count': 14}}
Devanahalli {1: {'mean': 4606.9148770709035, 'std': 456.2054151733658, 'count': 7}, 2: {'mean': 4936.153738448984, 'std': 478.78750862962505, 'count': 14}, 3: {'mean': 4865.343550039019, 'std': 459.80251272063725, 'count': 12}}
Devanahalli {1: {'mean': 4606.9148770709035, 'std': 456.2054151733658, 'count': 7}, 2: {'mean': 4936.153738448984, 'std': 478.78750862962505, 'count': 14}, 3: {'mean': 4865.343550039019, 'std': 459.80251272063725, 'count': 12}, 4: {'mean': 5981.308411214954, 'std': 0.0, 'count': 1}}
Devanahalli {1: {'mean': 4606.9148770709035, 'std': 456.2054151733658, 'count': 7}, 2: {'mean': 4936.153738448984, 'std': 478.78750862962505, 'count': 14}, 3: {'mean': 4865.343550039019, 'std': 459.80251272063725, 'count': 12}, 4: {'mean': 5981.308411214954, 'std': 0.0, 'count': 1}, 5: {'mean': 4166.666666666667, 'std': 0.0, 'count': 1}}
Devarachikkanahalli {1: {'mean': 3902.439024390244, 'std': 0.0, 'count': 1}}
Devarachikkanahalli {1: {'mean': 3902.439024390244, 'std': 0.0, 'count': 1}, 2: {'mean': 4326.739586439992, 'std': 1082.6324000628515, 'count': 9}}
Devarachikkanahalli {1: {'mean': 3902.439024390244, 'std': 0.0, 'count': 1}, 2: {'mean': 4326.739586439992, 'std': 1082.6324000628515, 'count': 9}, 3: {'mean': 4404.02899440667, 'std': 596.4161034790261, 'count': 5}}
Dodda Nekkundi {2: {'mean': 4271.409551033765, 'std': 572.5384233681566, 'count': 19}}
Dodda Nekkundi {2: {'mean': 4271.409551033765, 'std': 572.5384233681566, 'count': 19}, 3: {'mean': 5934.221068512782, 'std': 1020.763160342317, 'count': 7}}
Doddaballapur {1: {'mean': 7492.354740061162, 'std': 0.0, 'count': 1}}
Doddaballapur {1: {'mean': 7492.354740061162, 'std': 0.0, 'count': 1}, 3: {'mean': 6861.368629625442, 'std': 792.385913681854, 'count': 3}}
Doddaballapur {1: {'mean': 7492.354740061162, 'std': 0.0, 'count': 1}, 3: {'mean': 6861.368629625442, 'std': 792.385913681854, 'count': 3}, 4: {'mean': 7306.716419287801, 'std': 1508.6011290881638, 'count': 4}}
Doddakallasandra {2: {'mean': 4009.260011822078, 'std': 22.428701187061954, 'count': 6}}
Doddakallasandra {2: {'mean': 4009.260011822078, 'std': 22.428701187061954, 'count': 6}, 3: {'mean': 3999.4695049973843, 'std': 0.3068175498332698, 'count': 4}}
Doddathoguru {1: {'mean': 3193.939393939394, 'std': 145.7068518808643, 'count': 3}}
Doddathoguru {1: {'mean': 3193.939393939394, 'std': 145.7068518808643, 'count': 3}, 2: {'mean': 3695.715772231204, 'std': 513.1647769886983, 'count': 14}}
Doddathoguru {1: {'mean': 3193.939393939394, 'std': 145.7068518808643, 'count': 3}, 2: {'mean': 3695.715772231204, 'std': 513.1647769886983, 'count': 14}, 3: {'mean': 3920.463690699665, 'std': 643.1324346449559, 'count': 7}}
Domlur {1: {'mean': 9445.779914529914, 'std': 948.6331997307019, 'count': 3}}
Domlur {1: {'mean': 9445.779914529914, 'std': 948.6331997307019, 'count': 3}, 2: {'mean': 7329.742881854468, 'std': 773.8913545349003, 'count': 3}}
Domlur {1: {'mean': 9445.779914529914, 'std': 948.6331997307019, 'count': 3}, 2: {'mean': 7329.742881854468, 'std': 773.8913545349003, 'count': 3}, 3: {'mean': 8601.445470741792, 'std': 2229.6988314054834, 'count': 14}}
Dommasandra {2: {'mean': 3322.6608898241893, 'std': 544.174150775161, 'count': 8}}
Dommasandra {2: {'mean': 3322.6608898241893, 'std': 544.174150775161, 'count': 8}, 3: {'mean': 3313.5675560999007, 'std': 817.0930121375212, 'count': 3}}
Dommasandra {2: {'mean': 3322.6608898241893, 'std': 544.174150775161, 'count': 8}, 3: {'mean': 3313.5675560999007, 'std': 817.0930121375212, 'count': 3}, 4: {'mean': 2518.5185185185187, 'std': 0.0, 'count': 1}}
EPIP Zone {2: {'mean': 6352.512219589275, 'std': 547.9667498496266, 'count': 7}}
EPIP Zone {2: {'mean': 6352.512219589275, 'std': 547.9667498496266, 'count': 7}, 3: {'mean': 6961.117262886345, 'std': 262.90361114936303, 'count': 8}}
EPIP Zone {2: {'mean': 6352.512219589275, 'std': 547.9667498496266, 'count': 7}, 3: {'mean': 6961.117262886345, 'std': 262.90361114936303, 'count': 8}, 4: {'mean': 6621.198451923327, 'std': 53.43624500234158, 'count': 3}}
Electronic City {1: {'mean': 4328.254265940121, 'std': 1179.3241254681986, 'count': 20}}
Electronic City {1: {'mean': 4328.254265940121, 'std': 1179.3241254681986, 'count': 20}, 2: {'mean': 4223.573582626289, 'std': 1191.7527084954636, 'count': 179}}
Electronic City {1: {'mean': 4328.254265940121, 'std': 1179.3241254681986, 'count': 20}, 2: {'mean': 4223.573582626289, 'std': 1191.7527084954636, 'count': 179}, 3: {'mean': 4585.774797046123, 'std': 1204.6558833568274, 'count': 75}}
Electronic City {1: {'mean': 4328.254265940121, 'std': 1179.3241254681986, 'count': 20}, 2: {'mean': 4223.573582626289, 'std': 1191.7527084954636, 'count': 179}, 3: {'mean': 4585.774797046123, 'std': 1204.6558833568274, 'count': 75}, 4: {'mean': 5201.660222644956, 'std': 931.5912756321039, 'count': 5}}
Electronic City Phase II {1: {'mean': 4265.886287625418, 'std': 1022.5047171241084, 'count': 3}}
Electronic City Phase II {1: {'mean': 4265.886287625418, 'std': 1022.5047171241084, 'count': 3}, 2: {'mean': 3529.072049858916, 'std': 979.4555805604972, 'count': 71}}
Electronic City Phase II {1: {'mean': 4265.886287625418, 'std': 1022.5047171241084, 'count': 3}, 2: {'mean': 3529.072049858916, 'std': 979.4555805604972, 'count': 71}, 3: {'mean': 3506.772021417667, 'std': 922.6326003596901, 'count': 43}}
Electronic City Phase II {1: {'mean': 4265.886287625418, 'std': 1022.5047171241084, 'count': 3}, 2: {'mean': 3529.072049858916, 'std': 979.4555805604972, 'count': 71}, 3: {'mean': 3506.772021417667, 'std': 922.6326003596901, 'count': 43}, 4: {'mean': 4680.190258840645, 'std': 272.972080657902, 'count': 5}}
Electronics City Phase 1 {1: {'mean': 4522.306447815004, 'std': 635.4094144771141, 'count': 7}}
Electronics City Phase 1 {1: {'mean': 4522.306447815004, 'std': 635.4094144771141, 'count': 7}, 2: {'mean': 4842.116757845357, 'std': 498.05198255206807, 'count': 33}}
Electronics City Phase 1 {1: {'mean': 4522.306447815004, 'std': 635.4094144771141, 'count': 7}, 2: {'mean': 4842.116757845357, 'std': 498.05198255206807, 'count': 33}, 3: {'mean': 4851.575882244289, 'std': 533.2869033255906, 'count': 20}}
Frazer Town {1: {'mean': 11160.714285714286, 'std': 0.0, 'count': 1}}
Frazer Town {1: {'mean': 11160.714285714286, 'std': 0.0, 'count': 1}, 2: {'mean': 9256.913801828407, 'std': 830.6145881127068, 'count': 4}}
Frazer Town {1: {'mean': 11160.714285714286, 'std': 0.0, 'count': 1}, 2: {'mean': 9256.913801828407, 'std': 830.6145881127068, 'count': 4}, 3: {'mean': 9845.92937034917, 'std': 1554.2575050192804, 'count': 16}}
Frazer Town {1: {'mean': 11160.714285714286, 'std': 0.0, 'count': 1}, 2: {'mean': 9256.913801828407, 'std': 830.6145881127068, 'count': 4}, 3: {'mean': 9845.92937034917, 'std': 1554.2575050192804, 'count': 16}, 4: {'mean': 9580.08324073647, 'std': 1086.7606066839614, 'count': 6}}
GM Palaya {2: {'mean': 4065.297171500179, 'std': 228.5624776226282, 'count': 2}}
GM Palaya {2: {'mean': 4065.297171500179, 'std': 228.5624776226282, 'count': 2}, 3: {'mean': 4628.867942650349, 'std': 354.0596141419346, 'count': 6}}
Garudachar Palya {2: {'mean': 4567.292659219588, 'std': 35.16727856616533, 'count': 9}}
Garudachar Palya {2: {'mean': 4567.292659219588, 'std': 35.16727856616533, 'count': 9}, 3: {'mean': 4580.959776242796, 'std': 23.67431495380781, 'count': 6}}
Giri Nagar {3: {'mean': 15888.888888888889, 'std': 1888.8888888888887, 'count': 2}}
Giri Nagar {3: {'mean': 15888.888888888889, 'std': 1888.8888888888887, 'count': 2}, 4: {'mean': 17361.111111111113, 'std': 982.092751647982, 'count': 3}}
Giri Nagar {3: {'mean': 15888.888888888889, 'std': 1888.8888888888887, 'count': 2}, 4: {'mean': 17361.111111111113, 'std': 982.092751647982, 'count': 3}, 6: {'mean': 14583.333333333334, 'std': 2083.333333333334, 'count': 2}}
Gollarapalya Hosahalli {2: {'mean': 4170.472980827493, 'std': 176.69088584246873, 'count': 4}}
Gollarapalya Hosahalli {2: {'mean': 4170.472980827493, 'std': 176.69088584246873, 'count': 4}, 3: {'mean': 4351.161786961001, 'std': 159.71264119139414, 'count': 5}}
Gollarapalya Hosahalli {2: {'mean': 4170.472980827493, 'std': 176.69088584246873, 'count': 4}, 3: {'mean': 4351.161786961001, 'std': 159.71264119139414, 'count': 5}, 4: {'mean': 4514.435695538058, 'std': 0.0, 'count': 1}}
Gottigere {1: {'mean': 3201.9704433497536, 'std': 0.0, 'count': 2}}
Gottigere {1: {'mean': 3201.9704433497536, 'std': 0.0, 'count': 2}, 2: {'mean': 4187.198530290943, 'std': 615.4290329261535, 'count': 18}}
Gottigere {1: {'mean': 3201.9704433497536, 'std': 0.0, 'count': 2}, 2: {'mean': 4187.198530290943, 'std': 615.4290329261535, 'count': 18}, 3: {'mean': 4243.533192141064, 'std': 545.165771797653, 'count': 14}}

Gottigere {1: {'mean': 3201.9704433497536, 'std': 0.0, 'count': 2}, 2: {'mean': 4187.198530290943, 'std': 615.4290329261535, 'count': 18}, 3: {'mean': 4243.533192141064, 'std': 545.165771797653, 'count': 14}, 4: {'mean': 4433.333333333333, 'std': 286.74417556808754, 'count': 3}}
Green Glen Layout {2: {'mean': 5874.64951344219, 'std': 208.0884384424191, 'count': 3}}
Green Glen Layout {2: {'mean': 5874.64951344219, 'std': 208.0884384424191, 'count': 3}, 3: {'mean': 6639.764255543528, 'std': 469.4210339773065, 'count': 22}}
Green Glen Layout {2: {'mean': 5874.64951344219, 'std': 208.0884384424191, 'count': 3}, 3: {'mean': 6639.764255543528, 'std': 469.4210339773065, 'count': 22}, 4: {'mean': 6835.898556082042, 'std': 333.3960060843011, 'count': 4}}
Gubbalala {2: {'mean': 5018.120021443538, 'std': 616.24268015249, 'count': 4}}
Gubbalala {2: {'mean': 5018.120021443538, 'std': 616.24268015249, 'count': 4}, 3: {'mean': 5794.291811767968, 'std': 701.7168143003905, 'count': 7}}
Gubbalala {2: {'mean': 5018.120021443538, 'std': 616.24268015249, 'count': 4}, 3: {'mean': 5794.291811767968, 'std': 701.7168143003905, 'count': 7}, 4: {'mean': 4562.5, 'std': 312.5, 'count': 2}}
Gubbalala {2: {'mean': 5018.120021443538, 'std': 616.24268015249, 'count': 4}, 3: {'mean': 5794.291811767968, 'std': 701.7168143003905, 'count': 7}, 4: {'mean': 4562.5, 'std': 312.5, 'count': 2}, 5: {'mean': 5486.381322957199, 'std': 0.0, 'count': 1}}
Gunjur {2: {'mean': 3938.0120307679967, 'std': 369.34106505379697, 'count': 12}}
Gunjur {2: {'mean': 3938.0120307679967, 'std': 369.34106505379697, 'count': 12}, 3: {'mean': 4582.331403008516, 'std': 552.308800975027, 'count': 8}}
Gunjur {2: {'mean': 3938.0120307679967, 'std': 369.34106505379697, 'count': 12}, 3: {'mean': 4582.331403008516, 'std': 552.308800975027, 'count': 8}, 4: {'mean': 4750.0, 'std': 0.0, 'count': 1}}
HAL 2nd Stage {2: {'mean': 24166.666666666668, 'std': 0.0, 'count': 1}}
HAL 2nd Stage {2: {'mean': 24166.666666666668, 'std': 0.0, 'count': 1}, 3: {'mean': 19326.37335321899, 'std': 807.8548347004726, 'count': 2}}
HAL 2nd Stage {2: {'mean': 24166.666666666668, 'std': 0.0, 'count': 1}, 3: {'mean': 19326.37335321899, 'std': 807.8548347004726, 'count': 2}, 5: {'mean': 24509.803921568626, 'std': 0.0, 'count': 1}}
HBR Layout {2: {'mean': 6163.1658953574815, 'std': 1933.415341710632, 'count': 5}}
HBR Layout {2: {'mean': 6163.1658953574815, 'std': 1933.415341710632, 'count': 5}, 3: {'mean': 6718.224920185002, 'std': 1116.5076173869681, 'count': 6}}
HBR Layout {2: {'mean': 6163.1658953574815, 'std': 1933.415341710632, 'count': 5}, 3: {'mean': 6718.224920185002, 'std': 1116.5076173869681, 'count': 6}, 4: {'mean': 9791.666666666668, 'std': 208.33333333333303, 'count': 2}}
HRBR Layout {2: {'mean': 6827.946263617467, 'std': 966.9691792014793, 'count': 8}}
HRBR Layout {2: {'mean': 6827.946263617467, 'std': 966.9691792014793, 'count': 8}, 3: {'mean': 7143.374896079018, 'std': 1182.9430585167863, 'count': 4}}
HRBR Layout {2: {'mean': 6827.946263617467, 'std': 966.9691792014793, 'count': 8}, 3: {'mean': 7143.374896079018, 'std': 1182.9430585167863, 'count': 4}, 4: {'mean': 4736.8421052631575, 'std': 0.0, 'count': 1}}
HSR Layout {2: {'mean': 4739.236148532775, 'std': 918.5716205568192, 'count': 32}}
HSR Layout {2: {'mean': 4739.236148532775, 'std': 918.5716205568192, 'count': 32}, 3: {'mean': 4924.349382432697, 'std': 1111.9833342619856, 'count': 11}}
HSR Layout {2: {'mean': 4739.236148532775, 'std': 918.5716205568192, 'count': 32}, 3: {'mean': 4924.349382432697, 'std': 1111.9833342619856, 'count': 11}, 5: {'mean': 5833.333333333333, 'std': 0.0, 'count': 1}}
Haralur Road {1: {'mean': 6608.695652173913, 'std': 0.0, 'count': 1}}
Haralur Road {1: {'mean': 6608.695652173913, 'std': 0.0, 'count': 1}, 2: {'mean': 4442.431489020303, 'std': 902.0297287001697, 'count': 81}}
Haralur Road {1: {'mean': 6608.695652173913, 'std': 0.0, 'count': 1}, 2: {'mean': 4442.431489020303, 'std': 902.0297287001697, 'count': 81}, 3: {'mean': 5508.10108742305, 'std': 934.2074392416823, 'count': 39}}
Haralur Road {1: {'mean': 6608.695652173913, 'std': 0.0, 'count': 1}, 2: {'mean': 4442.431489020303, 'std': 902.0297287001697, 'count': 81}, 3: {'mean': 5508.10108742305, 'std': 934.2074392416823, 'count': 39}, 4: {'mean': 5788.002846826376, 'std': 573.618955205933, 'count': 6}}
Harlur {2: {'mean': 6137.381184467408, 'std': 760.3945168588826, 'count': 31}}
Harlur {2: {'mean': 6137.381184467408, 'std': 760.3945168588826, 'count': 31}, 3: {'mean': 6733.500810366982, 'std': 1010.6906117602452, 'count': 34}}
Harlur {2: {'mean': 6137.381184467408, 'std': 760.3945168588826, 'count': 31}, 3: {'mean': 6733.500810366982, 'std': 1010.6906117602452, 'count': 34}, 4: {'mean': 6806.220763959648, 'std': 749.5046631700119, 'count': 6}}
Hebbal {2: {'mean': 6772.820502785976, 'std': 1119.7042327288254, 'count': 41}}
Hebbal {2: {'mean': 6772.820502785976, 'std': 1119.7042327288254, 'count': 41}, 3: {'mean': 7101.464393512739, 'std': 1064.9549072670889, 'count': 63}}
Hebbal {2: {'mean': 6772.820502785976, 'std': 1119.7042327288254, 'count': 41}, 3: {'mean': 7101.464393512739, 'std': 1064.9549072670889, 'count': 63}, 4: {'mean': 8020.904932434183, 'std': 883.2866989126516, 'count': 24}}
Hebbal Kempapura {2: {'mean': 8716.498778998779, 'std': 1081.9219617716674, 'count': 4}}
Hebbal Kempapura {2: {'mean': 8716.498778998779, 'std': 1081.9219617716674, 'count': 4}, 3: {'mean': 9517.562179481964, 'std': 939.9188933583704, 'count': 13}}
Hebbal Kempapura {2: {'mean': 8716.498778998779, 'std': 1081.9219617716674, 'count': 4}, 3: {'mean': 9517.562179481964, 'std': 939.9188933583704, 'count': 13}, 4: {'mean': 8861.240238842134, 'std': 978.6206485541776, 'count': 4}}
Hebbal Kempapura {2: {'mean': 8716.498778998779, 'std': 1081.9219617716674, 'count': 4}, 3: {'mean': 9517.562179481964, 'std': 939.9188933583704, 'count': 13}, 4: {'mean': 8861.240238842134, 'std': 978.6206485541776, 'count': 4}, 5: {'mean': 8320.802005012532, 'std': 373.56532189325577, 'count': 3}}
Hegde Nagar {2: {'mean': 6157.975113248077, 'std': 728.8922268349711, 'count': 5}}
Hegde Nagar {2: {'mean': 6157.975113248077, 'std': 728.8922268349711, 'count': 5}, 3: {'mean': 6681.438863622023, 'std': 564.0312879402329, 'count': 27}}
Hegde Nagar {2: {'mean': 6157.975113248077, 'std': 728.8922268349711, 'count': 5}, 3: {'mean': 6681.438863622023, 'std': 564.0312879402329, 'count': 27}, 4: {'mean': 6916.666666666667, 'std': 0.0, 'count': 1}}
Hegde Nagar {2: {'mean': 6157.975113248077, 'std': 728.8922268349711, 'count': 5}, 3: {'mean': 6681.438863622023, 'std': 564.0312879402329, 'count': 27}, 4: {'mean': 6916.666666666667, 'std': 0.0, 'count': 1}, 6: {'mean': 7000.0, 'std': 0.0, 'count': 1}}
Hennur {2: {'mean': 4442.194358592492, 'std': 329.76870976065265, 'count': 36}}
Hennur {2: {'mean': 4442.194358592492, 'std': 329.76870976065265, 'count': 36}, 3: {'mean': 4809.551783721774, 'std': 731.3786843294923, 'count': 9}}
Hennur {2: {'mean': 4442.194358592492, 'std': 329.76870976065265, 'count': 36}, 3: {'mean': 4809.551783721774, 'std': 731.3786843294923, 'count': 9}, 4: {'mean': 4591.981802672733, 'std': 0.0, 'count': 1}}
Hennur {2: {'mean': 4442.194358592492, 'std': 329.76870976065265, 'count': 36}, 3: {'mean': 4809.551783721774, 'std': 731.3786843294923, 'count': 9}, 4: {'mean': 4591.981802672733, 'std': 0.0, 'count': 1}, 5: {'mean': 5000.0, 'std': 0.0, 'count': 1}}
Hennur Road {2: {'mean': 5664.294405842, 'std': 916.5454988680965, 'count': 55}}
Hennur Road {2: {'mean': 5664.294405842, 'std': 916.5454988680965, 'count': 55}, 3: {'mean': 6069.503411656876, 'std': 801.5978744613889, 'count': 71}}
Hennur Road {2: {'mean': 5664.294405842, 'std': 916.5454988680965, 'count': 55}, 3: {'mean': 6069.503411656876, 'std': 801.5978744613889, 'count': 71}, 4: {'mean': 6723.42350243022, 'std': 1360.2814958326924, 'count': 4}}
Hennur Road {2: {'mean': 5664.294405842, 'std': 916.5454988680965, 'count': 55}, 3: {'mean': 6069.503411656876, 'std': 801.5978744613889, 'count': 71}, 4: {'mean': 6723.42350243022, 'std': 1360.2814958326924, 'count': 4}, 5: {'mean': 7352.941176470588, 'std': 0.0, 'count': 1}}
Hennur Road {2: {'mean': 5664.294405842, 'std': 916.5454988680965, 'count': 55}, 3: {'mean': 6069.503411656876, 'std': 801.5978744613889, 'count': 71}, 4: {'mean': 6723.42350243022, 'std': 1360.2814958326924, 'count': 4}, 5: {'mean': 7352.941176470588, 'std': 0.0, 'count': 1}, 8: {'mean': 5000.0, 'std': 0.0, 'count': 1}}
Hoodi {1: {'mean': 5843.393365544693, 'std': 878.1416877495989, 'count': 3}}
Hoodi {1: {'mean': 5843.393365544693, 'std': 878.1416877495989, 'count': 3}, 2: {'mean': 5576.467924050863, 'std': 532.1742679272731, 'count': 24}}
Hoodi {1: {'mean': 5843.393365544693, 'std': 878.1416877495989, 'count': 3}, 2: {'mean': 5576.467924050863, 'std': 532.1742679272731, 'count': 24}, 3: {'mean': 5550.490547257157, 'std': 500.1454767018147, 'count': 20}}
Hoodi {1: {'mean': 5843.393365544693, 'std': 878.1416877495989, 'count': 3}, 2: {'mean': 5576.467924050863, 'std': 532.1742679272731, 'count': 24}, 3: {'mean': 5550.490547257157, 'std': 500.1454767018147, 'count': 20}, 4: {'mean': 5295.067358316983, 'std': 736.8679318376135, 'count': 4}}
Hoodi {1: {'mean': 5843.393365544693, 'std': 878.1416877495989, 'count': 3}, 2: {'mean': 5576.467924050863, 'std': 532.1742679272731, 'count': 24}, 3: {'mean': 5550.490547257157, 'std': 500.1454767018147, 'count': 20}, 4: {'mean': 5295.067358316983, 'std': 736.8679318376135, 'count': 4}, 5: {'mean': 6666.666666666667, 'std': 0.0, 'count': 1}}
Horamavu Agara {1: {'mean': 4320.0, 'std': 0.0, 'count': 1}}
Horamavu Agara {1: {'mean': 4320.0, 'std': 0.0, 'count': 1}, 2: {'mean': 4129.887794312633, 'std': 508.3758300561651, 'count': 19}}
Horamavu Agara {1: {'mean': 4320.0, 'std': 0.0, 'count': 1}, 2: {'mean': 4129.887794312633, 'std': 508.3758300561651, 'count': 19}, 3: {'mean': 4621.353464796817, 'std': 511.44214228185155, 'count': 9}}
Horamavu Agara {1: {'mean': 4320.0, 'std': 0.0, 'count': 1}, 2: {'mean': 4129.887794312633, 'std': 508.3758300561651, 'count': 19}, 3: {'mean': 4621.353464796817, 'std': 511.44214228185155, 'count': 9}, 5: {'mean': 3333.3333333333335, 'std': 0.0, 'count': 1}}
Horamavu Banaswadi {2: {'mean': 4195.182184632629, 'std': 472.40961899077587, 'count': 20}}
Horamavu Banaswadi {2: {'mean': 4195.182184632629, 'std': 472.40961899077587, 'count': 20}, 3: {'mean': 3953.2300960525395, 'std': 297.2652996762272, 'count': 3}}
Horamavu Banaswadi {2: {'mean': 4195.182184632629, 'std': 472.40961899077587, 'count': 20}, 3: {'mean': 3953.2300960525395, 'std': 297.2652996762272, 'count': 3}, 6: {'mean': 5263.1578947368425, 'std': 0.0, 'count': 1}}
Hormavu {1: {'mean': 4386.46711095142, 'std': 463.4471257552693, 'count': 2}}
Hormavu {1: {'mean': 4386.46711095142, 'std': 463.4471257552693, 'count': 2}, 2: {'mean': 4720.617954190519, 'std': 721.7719786205827, 'count': 40}}
Hormavu {1: {'mean': 4386.46711095142, 'std': 463.4471257552693, 'count': 2}, 2: {'mean': 4720.617954190519, 'std': 721.7719786205827, 'count': 40}, 3: {'mean': 4427.642898747908, 'std': 504.41094830524696, 'count': 12}}
Hormavu {1: {'mean': 4386.46711095142, 'std': 463.4471257552693, 'count': 2}, 2: {'mean': 4720.617954190519, 'std': 721.7719786205827, 'count': 40}, 3: {'mean': 4427.642898747908, 'std': 504.41094830524696, 'count': 12}, 4: {'mean': 5039.439088518843, 'std': 0.0, 'count': 1}}
Hosa Road {1: {'mean': 4799.375, 'std': 199.375, 'count': 2}}
Hosa Road {1: {'mean': 4799.375, 'std': 199.375, 'count': 2}, 2: {'mean': 4946.270140994979, 'std': 834.9741219397788, 'count': 19}}
Hosa Road {1: {'mean': 4799.375, 'std': 199.375, 'count': 2}, 2: {'mean': 4946.270140994979, 'std': 834.9741219397788, 'count': 19}, 3: {'mean': 5382.16497047624, 'std': 896.2587581277162, 'count': 15}}
Hosa Road {1: {'mean': 4799.375, 'std': 199.375, 'count': 2}, 2: {'mean': 4946.270140994979, 'std': 834.9741219397788, 'count': 19}, 3: {'mean': 5382.16497047624, 'std': 896.2587581277162, 'count': 15}, 4: {'mean': 3750.0, 'std': 0.0, 'count': 1}}
Hosakerehalli {2: {'mean': 7132.2680042005195, 'std': 2396.0521058736667, 'count': 4}}
Hosakerehalli {2: {'mean': 7132.2680042005195, 'std': 2396.0521058736667, 'count': 4}, 3: {'mean': 9162.737420366177, 'std': 1759.0622093546074, 'count': 9}}
Hosakerehalli {2: {'mean': 7132.2680042005195, 'std': 2396.0521058736667, 'count': 4}, 3: {'mean': 9162.737420366177, 'std': 1759.0622093546074, 'count': 9}, 4: {'mean': 10348.082968582745, 'std': 1380.1349845751727, 'count': 5}}
Hosakerehalli {2: {'mean': 7132.2680042005195, 'std': 2396.0521058736667, 'count': 4}, 3: {'mean': 9162.737420366177, 'std': 1759.0622093546074, 'count': 9}, 4: {'mean': 10348.082968582745, 'std': 1380.1349845751727, 'count': 5}, 5: {'mean': 10041.666666666666, 'std': 375.0, 'count': 2}}

Hoskote {1: {'mean': 4518.664047151277, 'std': 0.0, 'count': 1}}
Hoskote {1: {'mean': 4518.664047151277, 'std': 0.0, 'count': 1}, 2: {'mean': 3174.4098068983926, 'std': 410.28654938450563, 'count': 7}}
Hoskote {1: {'mean': 4518.664047151277, 'std': 0.0, 'count': 1}, 2: {'mean': 3174.4098068983926, 'std': 410.28654938450563, 'count': 7}, 3: {'mean': 3600.5359456638253, 'std': 751.6624895989765, 'count': 8}}
Hosur Road {1: {'mean': 4565.217391304348, 'std': 0.0, 'count': 1}}
Hosur Road {1: {'mean': 4565.217391304348, 'std': 0.0, 'count': 1}, 2: {'mean': 5644.8823512611825, 'std': 1217.5145047356148, 'count': 9}}
Hosur Road {1: {'mean': 4565.217391304348, 'std': 0.0, 'count': 1}, 2: {'mean': 5644.8823512611825, 'std': 1217.5145047356148, 'count': 9}, 3: {'mean': 5646.277406311303, 'std': 1116.583963171691, 'count': 14}}
Hosur Road {1: {'mean': 4565.217391304348, 'std': 0.0, 'count': 1}, 2: {'mean': 5644.8823512611825, 'std': 1217.5145047356148, 'count': 9}, 3: {'mean': 5646.277406311303, 'std': 1116.583963171691, 'count': 14}, 4: {'mean': 5916.666666666666, 'std': 583.3333333333335, 'count': 2}}
Hosur Road {1: {'mean': 4565.217391304348, 'std': 0.0, 'count': 1}, 2: {'mean': 5644.8823512611825, 'std': 1217.5145047356148, 'count': 9}, 3: {'mean': 5646.277406311303, 'std': 1116.583963171691, 'count': 14}, 4: {'mean': 5916.666666666666, 'std': 583.3333333333335, 'count': 2}, 5: {'mean': 6136.363636363636, 'std': 1136.3636363636365, 'count': 2}}
Hulimavu {1: {'mean': 5567.760150976738, 'std': 1222.422984550909, 'count': 3}}
Hulimavu {1: {'mean': 5567.760150976738, 'std': 1222.422984550909, 'count': 3}, 2: {'mean': 5327.300781142056, 'std': 1646.506992767097, 'count': 28}}
Hulimavu {1: {'mean': 5567.760150976738, 'std': 1222.422984550909, 'count': 3}, 2: {'mean': 5327.300781142056, 'std': 1646.506992767097, 'count': 28}, 3: {'mean': 6041.97465739293, 'std': 1516.4558507527224, 'count': 12}}
Hulimavu {1: {'mean': 5567.760150976738, 'std': 1222.422984550909, 'count': 3}, 2: {'mean': 5327.300781142056, 'std': 1646.506992767097, 'count': 28}, 3: {'mean': 6041.97465739293, 'std': 1516.4558507527224, 'count': 12}, 4: {'mean': 6608.14606741573, 'std': 1435.7649478084438, 'count': 4}}
ISRO Layout {2: {'mean': 5315.980629539952, 'std': 702.3075360678213, 'count': 4}}
ISRO Layout {2: {'mean': 5315.980629539952, 'std': 702.3075360678213, 'count': 4}, 3: {'mean': 5770.6023290800695, 'std': 579.7626344235805, 'count': 2}}
ISRO Layout {2: {'mean': 5315.980629539952, 'std': 702.3075360678213, 'count': 4}, 3: {'mean': 5770.6023290800695, 'std': 579.7626344235805, 'count': 2}, 4: {'mean': 6071.428571428572, 'std': 0.0, 'count': 1}}
ISRO Layout {2: {'mean': 5315.980629539952, 'std': 702.3075360678213, 'count': 4}, 3: {'mean': 5770.6023290800695, 'std': 579.7626344235805, 'count': 2}, 4: {'mean': 6071.428571428572, 'std': 0.0, 'count': 1}, 6: {'mean': 5681.818181818182, 'std': 0.0, 'count': 1}}
ITPL {3: {'mean': 4935.497846683894, 'std': 605.1521192031312, 'count': 6}}
ITPL {3: {'mean': 4935.497846683894, 'std': 605.1521192031312, 'count': 6}, 4: {'mean': 5293.33921482135, 'std': 0.0, 'count': 1}}
Iblur Village {3: {'mean': 7091.009765176507, 'std': 410.88523168233667, 'count': 11}}
Iblur Village {3: {'mean': 7091.009765176507, 'std': 410.88523168233667, 'count': 11}, 4: {'mean': 7574.388209121246, 'std': 450.32403519924213, 'count': 8}}
Iblur Village {3: {'mean': 7091.009765176507, 'std': 410.88523168233667, 'count': 11}, 4: {'mean': 7574.388209121246, 'std': 450.32403519924213, 'count': 8}, 5: {'mean': 7753.573598412542, 'std': 47.31793204808173, 'count': 2}}
Indira Nagar {1: {'mean': 9254.901960784313, 'std': 3358.3833829030023, 'count': 3}}
Indira Nagar {1: {'mean': 9254.901960784313, 'std': 3358.3833829030023, 'count': 3}, 2: {'mean': 9702.969857242164, 'std': 1533.2274929574173, 'count': 11}}
Indira Nagar {1: {'mean': 9254.901960784313, 'std': 3358.3833829030023, 'count': 3}, 2: {'mean': 9702.969857242164, 'std': 1533.2274929574173, 'count': 11}, 3: {'mean': 11041.107173918466, 'std': 2774.468606570783, 'count': 15}}
Indira Nagar {1: {'mean': 9254.901960784313, 'std': 3358.3833829030023, 'count': 3}, 2: {'mean': 9702.969857242164, 'std': 1533.2274929574173, 'count': 11}, 3: {'mean': 11041.107173918466, 'std': 2774.468606570783, 'count': 15}, 4: {'mean': 14277.01762523191, 'std': 4557.109914183873, 'count': 7}}
Indira Nagar {1: {'mean': 9254.901960784313, 'std': 3358.3833829030023, 'count': 3}, 2: {'mean': 9702.969857242164, 'std': 1533.2274929574173, 'count': 11}, 3: {'mean': 11041.107173918466, 'std': 2774.468606570783, 'count': 15}, 4: {'mean': 14277.01762523191, 'std': 4557.109914183873, 'count': 7}, 5: {'mean': 19444.444444444445, 'std': 0.0, 'count': 1}}
Indira Nagar {1: {'mean': 9254.901960784313, 'std': 3358.3833829030023, 'count': 3}, 2: {'mean': 9702.969857242164, 'std': 1533.2274929574173, 'count': 11}, 3: {'mean': 11041.107173918466, 'std': 2774.468606570783, 'count': 15}, 4: {'mean': 14277.01762523191, 'std': 4557.109914183873, 'count': 7}, 5: {'mean': 19444.444444444445, 'std': 0.0, 'count': 1}, 6: {'mean': 19791.666666666668, 'std': 0.0, 'count': 1}}
Indira Nagar {1: {'mean': 9254.901960784313, 'std': 3358.3833829030023, 'count': 3}, 2: {'mean': 9702.969857242164, 'std': 1533.2274929574173, 'count': 11}, 3: {'mean': 11041.107173918466, 'std': 2774.468606570783, 'count': 15}, 4: {'mean': 14277.01762523191, 'std': 4557.109914183873, 'count': 7}, 5: {'mean': 19444.444444444445, 'std': 0.0, 'count': 1}, 6: {'mean': 19791.666666666668, 'std': 0.0, 'count': 1}, 8: {'mean': 18461.53846153846, 'std': 0.0, 'count': 1}}
JP Nagar {1: {'mean': 5263.492063492064, 'std': 1239.2261826930576, 'count': 3}}
JP Nagar {1: {'mean': 5263.492063492064, 'std': 1239.2261826930576, 'count': 3}, 2: {'mean': 5819.199271378629, 'std': 1232.0361066103821, 'count': 18}}
JP Nagar {1: {'mean': 5263.492063492064, 'std': 1239.2261826930576, 'count': 3}, 2: {'mean': 5819.199271378629, 'std': 1232.0361066103821, 'count': 18}, 3: {'mean': 6120.005408172573, 'std': 1312.8659803453609, 'count': 20}}
JP Nagar {1: {'mean': 5263.492063492064, 'std': 1239.2261826930576, 'count': 3}, 2: {'mean': 5819.199271378629, 'std': 1232.0361066103821, 'count': 18}, 3: {'mean': 6120.005408172573, 'std': 1312.8659803453609, 'count': 20}, 4: {'mean': 5386.813709590226, 'std': 819.3589330387586, 'count': 5}}
JP Nagar {1: {'mean': 5263.492063492064, 'std': 1239.2261826930576, 'count': 3}, 2: {'mean': 5819.199271378629, 'std': 1232.0361066103821, 'count': 18}, 3: {'mean': 6120.005408172573, 'std': 1312.8659803453609, 'count': 20}, 4: {'mean': 5386.813709590226, 'std': 819.3589330387586, 'count': 5}, 5: {'mean': 6793.478260869565, 'std': 0.0, 'count': 1}}
JP Nagar {1: {'mean': 5263.492063492064, 'std': 1239.2261826930576, 'count': 3}, 2: {'mean': 5819.199271378629, 'std': 1232.0361066103821, 'count': 18}, 3: {'mean': 6120.005408172573, 'std': 1312.8659803453609, 'count': 20}, 4: {'mean': 5386.813709590226, 'std': 819.3589330387586, 'count': 5}, 5: {'mean': 6793.478260869565, 'std': 0.0, 'count': 1}, 6: {'mean': 3777.777777777778, 'std': 0.0, 'count': 1}}
JP Nagar {1: {'mean': 5263.492063492064, 'std': 1239.2261826930576, 'count': 3}, 2: {'mean': 5819.199271378629, 'std': 1232.0361066103821, 'count': 18}, 3: {'mean': 6120.005408172573, 'std': 1312.8659803453609, 'count': 20}, 4: {'mean': 5386.813709590226, 'std': 819.3589330387586, 'count': 5}, 5: {'mean': 6793.478260869565, 'std': 0.0, 'count': 1}, 6: {'mean': 3777.777777777778, 'std': 0.0, 'count': 1}, 7: {'mean': 5925.925925925926, 'std': 0.0, 'count': 1}}
Jakkur {2: {'mean': 6150.231012322482, 'std': 547.1996091951384, 'count': 21}}
Jakkur {2: {'mean': 6150.231012322482, 'std': 547.1996091951384, 'count': 21}, 3: {'mean': 6314.10646436659, 'std': 697.7935991872304, 'count': 27}}
Jakkur {2: {'mean': 6150.231012322482, 'std': 547.1996091951384, 'count': 21}, 3: {'mean': 6314.10646436659, 'std': 697.7935991872304, 'count': 27}, 4: {'mean': 7290.394789156389, 'std': 914.7687249133417, 'count': 5}}
Jalahalli {1: {'mean': 6656.504065040651, 'std': 856.2509031207591, 'count': 4}}
Jalahalli {1: {'mean': 6656.504065040651, 'std': 856.2509031207591, 'count': 4}, 2: {'mean': 6419.206421173111, 'std': 837.6548293126691, 'count': 12}}
Jalahalli {1: {'mean': 6656.504065040651, 'std': 856.2509031207591, 'count': 4}, 2: {'mean': 6419.206421173111, 'std': 837.6548293126691, 'count': 12}, 3: {'mean': 6351.724037140902, 'std': 708.5723247593588, 'count': 19}}
Jalahalli {1: {'mean': 6656.504065040651, 'std': 856.2509031207591, 'count': 4}, 2: {'mean': 6419.206421173111, 'std': 837.6548293126691, 'count': 12}, 3: {'mean': 6351.724037140902, 'std': 708.5723247593588, 'count': 19}, 4: {'mean': 7500.0, 'std': 0.0, 'count': 1}}
Jalahalli East {1: {'mean': 4866.666666666666, 'std': 466.6666666666665, 'count': 2}}
Jalahalli East {1: {'mean': 4866.666666666666, 'std': 466.6666666666665, 'count': 2}, 2: {'mean': 5327.76807092474, 'std': 253.50233403050984, 'count': 3}}
Jalahalli East {1: {'mean': 4866.666666666666, 'std': 466.6666666666665, 'count': 2}, 2: {'mean': 5327.76807092474, 'std': 253.50233403050984, 'count': 3}, 3: {'mean': 4804.029304029304, 'std': 42.12454212454213, 'count': 2}}
Jigani {2: {'mean': 5380.205408855938, 'std': 610.3583738561084, 'count': 19}}
Jigani {2: {'mean': 5380.205408855938, 'std': 610.3583738561084, 'count': 19}, 3: {'mean': 5118.341784477213, 'std': 569.9332571864948, 'count': 22}}
Jigani {2: {'mean': 5380.205408855938, 'std': 610.3583738561084, 'count': 19}, 3: {'mean': 5118.341784477213, 'std': 569.9332571864948, 'count': 22}, 4: {'mean': 5251.539444638085, 'std': 0.0, 'count': 1}}
Judicial Layout {2: {'mean': 4351.406771578446, 'std': 93.03767286599896, 'count': 2}}
Judicial Layout {2: {'mean': 4351.406771578446, 'std': 93.03767286599896, 'count': 2}, 3: {'mean': 6895.570698128242, 'std': 1721.3302715968377, 'count': 5}}
Judicial Layout {2: {'mean': 4351.406771578446, 'std': 93.03767286599896, 'count': 2}, 3: {'mean': 6895.570698128242, 'std': 1721.3302715968377, 'count': 5}, 4: {'mean': 10800.0, 'std': 0.0, 'count': 1}}
Judicial Layout {2: {'mean': 4351.406771578446, 'std': 93.03767286599896, 'count': 2}, 3: {'mean': 6895.570698128242, 'std': 1721.3302715968377, 'count': 5}, 4: {'mean': 10800.0, 'std': 0.0, 'count': 1}, 5: {'mean': 12962.962962962964, 'std': 0.0, 'count': 1}}
KR Puram {1: {'mean': 3496.4985994397757, 'std': 425.0700280112044, 'count': 2}}
KR Puram {1: {'mean': 3496.4985994397757, 'std': 425.0700280112044, 'count': 2}, 2: {'mean': 4334.439122287065, 'std': 915.4655005942303, 'count': 51}}
KR Puram {1: {'mean': 3496.4985994397757, 'std': 425.0700280112044, 'count': 2}, 2: {'mean': 4334.439122287065, 'std': 915.4655005942303, 'count': 51}, 3: {'mean': 4342.182026781063, 'std': 795.5697199258738, 'count': 12}}
KR Puram {1: {'mean': 3496.4985994397757, 'std': 425.0700280112044, 'count': 2}, 2: {'mean': 4334.439122287065, 'std': 915.4655005942303, 'count': 51}, 3: {'mean': 4342.182026781063, 'std': 795.5697199258738, 'count': 12}, 4: {'mean': 6332.435279343688, 'std': 732.1215615521066, 'count': 3}}
KR Puram {1: {'mean': 3496.4985994397757, 'std': 425.0700280112044, 'count': 2}, 2: {'mean': 4334.439122287065, 'std': 915.4655005942303, 'count': 51}, 3: {'mean': 4342.182026781063, 'std': 795.5697199258738, 'count': 12}, 4: {'mean': 6332.435279343688, 'std': 732.1215615521066, 'count': 3}, 6: {'mean': 4159.883720930233, 'std': 90.11627906976742, 'count': 2}}
KR Puram {1: {'mean': 3496.4985994397757, 'std': 425.0700280112044, 'count': 2}, 2: {'mean': 4334.439122287065, 'std': 915.4655005942303, 'count': 51}, 3: {'mean': 4342.182026781063, 'std': 795.5697199258738, 'count': 12}, 4: {'mean': 6332.435279343688, 'std': 732.1215615521066, 'count': 3}, 6: {'mean': 4159.883720930233, 'std': 90.11627906976742, 'count': 2}, 7: {'mean': 3928.5714285714284, 'std': 0.0, 'count': 1}}
KR Puram {1: {'mean': 3496.4985994397757, 'std': 425.0700280112044, 'count': 2}, 2: {'mean': 4334.439122287065, 'std': 915.4655005942303, 'count': 51}, 3: {'mean': 4342.182026781063, 'std': 795.5697199258738, 'count': 12}, 4: {'mean': 6332.435279343688, 'std': 732.1215615521066, 'count': 3}, 6: {'mean': 4159.883720930233, 'std': 90.11627906976742, 'count': 2}, 7: {'mean': 3928.5714285714284, 'std': 0.0, 'count': 1}, 9: {'mean': 4347.826086956522, 'std': 0.0, 'count': 1}}
Kadubeesanahalli {2: {'mean': 6376.103144106457, 'std': 1495.108114630899, 'count': 5}}
Kadubeesanahalli {2: {'mean': 6376.103144106457, 'std': 1495.108114630899, 'count': 5}, 3: {'mean': 5422.047214586422, 'std': 1213.899445999799, 'count': 5}}
Kadugodi {1: {'mean': 4400.000000000001, 'std': 0.0, 'count': 1}}
Kadugodi {1: {'mean': 4400.000000000001, 'std': 0.0, 'count': 1}, 2: {'mean': 4953.281534393949, 'std': 838.7316907969797, 'count': 12}}
Kadugodi {1: {'mean': 4400.000000000001, 'std': 0.0, 'count': 1}, 2: {'mean': 4953.281534393949, 'std': 838.7316907969797, 'count': 12}, 3: {'mean': 5463.116924408958, 'std': 1023.8107822041367, 'count': 17}}
Kadugodi {1: {'mean': 4400.000000000001, 'std': 0.0, 'count': 1}, 2: {'mean': 4953.281534393949, 'std': 838.7316907969797, 'count': 12}, 3: {'mean': 5463.116924408958, 'std': 1023.8107822041367, 'count': 17}, 4: {'mean': 5033.333333333334, 'std': 566.6666666666665, 'count': 2}}
Kaggadasapura {2: {'mean': 4174.759774030046, 'std': 487.0889998502448, 'count': 26}}
Kaggadasapura {2: {'mean': 4174.759774030046, 'std': 487.0889998502448, 'count': 26}, 3: {'mean': 4487.237700661079, 'std': 479.5564957704774, 'count': 19}}
Kaggadasapura {2: {'mean': 4174.759774030046, 'std': 487.0889998502448, 'count': 26}, 3: {'mean': 4487.237700661079, 'std': 479.5564957704774, 'count': 19}, 4: {'mean': 4390.180878552972, 'std': 194.09107967146167, 'count': 3}}
Kaggalipura {1: {'mean': 5190.476190476191, 'std': 178.1741612749495, 'count': 3}}
Kaggalipura {1: {'mean': 5190.476190476191, 'std': 178.1741612749495, 'count': 3}, 2: {'mean': 5385.964912280701, 'std': 574.6785738301475, 'count': 6}}
Kaggalipura {1: {'mean': 5190.476190476191, 'std': 178.1741612749495, 'count': 3}, 2: {'mean': 5385.964912280701, 'std': 574.6785738301475, 'count': 6}, 3: {'mean': 5067.840459935322, 'std': 267.71813441909836, 'count': 5}}
Kaikondrahalli {2: {'mean': 5675.825039659637, 'std': 894.8552060211639, 'count': 5}}
Kaikondrahalli {2: {'mean': 5675.825039659637, 'std': 894.8552060211639, 'count': 5}, 3: {'mean': 6016.671751785143, 'std': 868.6732750797345, 'count': 4}}
Kaikondrahalli {2: {'mean': 5675.825039659637, 'std': 894.8552060211639, 'count': 5}, 3: {'mean': 6016.671751785143, 'std': 868.6732750797345, 'count': 4}, 4: {'mean': 6352.941176470588, 'std': 0.0, 'count': 1}}
Kaikondrahalli {2: {'mean': 5675.825039659637, 'std': 894.8552060211639, 'count': 5}, 3: {'mean': 6016.671751785143, 'std': 868.6732750797345, 'count': 4}, 4: {'mean': 6352.941176470588, 'std': 0.0, 'count': 1}, 6: {'mean': 6654.835847382431, 'std': 0.0, 'count': 1}}
Kalena Agrahara {1: {'mean': 6393.44262295082, 'std': 0.0, 'count': 1}}
Kalena Agrahara {1: {'mean': 6393.44262295082, 'std': 0.0, 'count': 1}, 2: {'mean': 4600.862878074762, 'std': 691.1688086769439, 'count': 13}}
Kalena Agrahara {1: {'mean': 6393.44262295082, 'std': 0.0, 'count': 1}, 2: {'mean': 4600.862878074762, 'std': 691.1688086769439, 'count': 13}, 3: {'mean': 5540.391844954946, 'std': 782.6421967834364, 'count': 8}}
Kalyan nagar {2: {'mean': 5174.290674954962, 'std': 959.8682778268459, 'count': 8}}
Kalyan nagar {2: {'mean': 5174.290674954962, 'std': 959.8682778268459, 'count': 8}, 3: {'mean': 5403.789409758371, 'std': 1008.9411534967034, 'count': 5}}
Kalyan nagar {2: {'mean': 5174.290674954962, 'std': 959.8682778268459, 'count': 8}, 3: {'mean': 5403.789409758371, 'std': 1008.9411534967034, 'count': 5}, 4: {'mean': 7043.982789343301, 'std': 850.7540527619626, 'count': 2}}

Kambipura {2: {'mean': 4617.214043035106, 'std': 371.95620126318187, 'count': 13}}
Kambipura {2: {'mean': 4617.214043035106, 'std': 371.95620126318187, 'count': 13}, 3: {'mean': 4613.88537985688, 'std': 442.39294983399617, 'count': 7}}
Kammanahalli {1: {'mean': 8428.57142857143, 'std': 0.0, 'count': 1}}
Kammanahalli {1: {'mean': 8428.57142857143, 'std': 0.0, 'count': 1}, 2: {'mean': 6384.469696969697, 'std': 537.9688091548688, 'count': 4}}
Kammanahalli {1: {'mean': 8428.57142857143, 'std': 0.0, 'count': 1}, 2: {'mean': 6384.469696969697, 'std': 537.9688091548688, 'count': 4}, 4: {'mean': 6896.551724137931, 'std': 0.0, 'count': 1}}
Kammanahalli {1: {'mean': 8428.57142857143, 'std': 0.0, 'count': 1}, 2: {'mean': 6384.469696969697, 'std': 537.9688091548688, 'count': 4}, 4: {'mean': 6896.551724137931, 'std': 0.0, 'count': 1}, 5: {'mean': 6962.25766229163, 'std': 2041.3437782846004, 'count': 2}}
Kammasandra {1: {'mean': 2916.3934426229507, 'std': 116.39344262295072, 'count': 2}}
Kammasandra {1: {'mean': 2916.3934426229507, 'std': 116.39344262295072, 'count': 2}, 2: {'mean': 3227.8474191127148, 'std': 607.9293263487696, 'count': 15}}
Kammasandra {1: {'mean': 2916.3934426229507, 'std': 116.39344262295072, 'count': 2}, 2: {'mean': 3227.8474191127148, 'std': 607.9293263487696, 'count': 15}, 3: {'mean': 3237.2655812105695, 'std': 861.3497493389445, 'count': 7}}
Kanakapura {1: {'mean': 5096.602546756389, 'std': 417.85606461579323, 'count': 5}}
Kanakapura {1: {'mean': 5096.602546756389, 'std': 417.85606461579323, 'count': 5}, 2: {'mean': 4604.465395835363, 'std': 480.2703857860582, 'count': 11}}
Kanakapura {1: {'mean': 5096.602546756389, 'std': 417.85606461579323, 'count': 5}, 2: {'mean': 4604.465395835363, 'std': 480.2703857860582, 'count': 11}, 3: {'mean': 4969.70888132023, 'std': 588.0621061875769, 'count': 10}}
Kanakapura {1: {'mean': 5096.602546756389, 'std': 417.85606461579323, 'count': 5}, 2: {'mean': 4604.465395835363, 'std': 480.2703857860582, 'count': 11}, 3: {'mean': 4969.70888132023, 'std': 588.0621061875769, 'count': 10}, 4: {'mean': 5633.802816901409, 'std': 0.0, 'count': 1}}
Kanakpura Road {1: {'mean': 5097.459088452888, 'std': 461.5048530031646, 'count': 24}}
Kanakpura Road {1: {'mean': 5097.459088452888, 'std': 461.5048530031646, 'count': 24}, 2: {'mean': 5077.534783602533, 'std': 516.3940902831463, 'count': 72}}
Kanakpura Road {1: {'mean': 5097.459088452888, 'std': 461.5048530031646, 'count': 24}, 2: {'mean': 5077.534783602533, 'std': 516.3940902831463, 'count': 72}, 3: {'mean': 4858.246912079384, 'std': 543.4220740323643, 'count': 97}}
Kanakpura Road {1: {'mean': 5097.459088452888, 'std': 461.5048530031646, 'count': 24}, 2: {'mean': 5077.534783602533, 'std': 516.3940902831463, 'count': 72}, 3: {'mean': 4858.246912079384, 'std': 543.4220740323643, 'count': 97}, 4: {'mean': 5754.468754468755, 'std': 642.9894850839651, 'count': 3}}
Kannamangala {2: {'mean': 5781.957506095438, 'std': 175.0239571773057, 'count': 6}}
Kannamangala {2: {'mean': 5781.957506095438, 'std': 175.0239571773057, 'count': 6}, 3: {'mean': 6165.072841663136, 'std': 431.9125650497451, 'count': 3}}
Kannamangala {2: {'mean': 5781.957506095438, 'std': 175.0239571773057, 'count': 6}, 3: {'mean': 6165.072841663136, 'std': 431.9125650497451, 'count': 3}, 4: {'mean': 5885.74639875218, 'std': 555.9126968865866, 'count': 3}}
Karuna Nagar {2: {'mean': 6149.479659413434, 'std': 0.0, 'count': 1}}
Karuna Nagar {2: {'mean': 6149.479659413434, 'std': 0.0, 'count': 1}, 3: {'mean': 7548.041260232853, 'std': 960.2983417649926, 'count': 6}}
Kasavanhalli {1: {'mean': 5690.909090909091, 'std': 0.0, 'count': 1}}
Kasavanhalli {1: {'mean': 5690.909090909091, 'std': 0.0, 'count': 1}, 2: {'mean': 5662.49327495964, 'std': 922.1542751438931, 'count': 31}}
Kasavanhalli {1: {'mean': 5690.909090909091, 'std': 0.0, 'count': 1}, 2: {'mean': 5662.49327495964, 'std': 922.1542751438931, 'count': 31}, 3: {'mean': 5761.689498642713, 'std': 998.0178355092115, 'count': 32}}
Kasavanhalli {1: {'mean': 5690.909090909091, 'std': 0.0, 'count': 1}, 2: {'mean': 5662.49327495964, 'std': 922.1542751438931, 'count': 31}, 3: {'mean': 5761.689498642713, 'std': 998.0178355092115, 'count': 32}, 4: {'mean': 7188.150786398397, 'std': 888.4937505820675, 'count': 6}}
Kasturi Nagar {2: {'mean': 6041.583372234744, 'std': 653.8682870762742, 'count': 6}}
Kasturi Nagar {2: {'mean': 6041.583372234744, 'std': 653.8682870762742, 'count': 6}, 3: {'mean': 5916.740546308524, 'std': 721.5559950179522, 'count': 5}}
Kasturi Nagar {2: {'mean': 6041.583372234744, 'std': 653.8682870762742, 'count': 6}, 3: {'mean': 5916.740546308524, 'std': 721.5559950179522, 'count': 5}, 4: {'mean': 6387.757738248516, 'std': 205.06926597089296, 'count': 2}}
Kathriguppe {2: {'mean': 5500.0, 'std': 0.0, 'count': 1}}
Kathriguppe {2: {'mean': 5500.0, 'std': 0.0, 'count': 1}, 3: {'mean': 5791.147903867093, 'std': 283.9730475517742, 'count': 18}}
Kaval Byrasandra {1: {'mean': 5208.333333333333, 'std': 0.0, 'count': 1}}
Kaval Byrasandra {1: {'mean': 5208.333333333333, 'std': 0.0, 'count': 1}, 2: {'mean': 4651.883076314409, 'std': 642.90451560445, 'count': 13}}
Kaval Byrasandra {1: {'mean': 5208.333333333333, 'std': 0.0, 'count': 1}, 2: {'mean': 4651.883076314409, 'std': 642.90451560445, 'count': 13}, 3: {'mean': 5264.778325123152, 'std': 92.36453201970426, 'count': 2}}
Kenchenahalli {1: {'mean': 5646.853146853147, 'std': 646.8531468531469, 'count': 2}}
Kenchenahalli {1: {'mean': 5646.853146853147, 'std': 646.8531468531469, 'count': 2}, 2: {'mean': 5274.4401769080805, 'std': 359.1996745553106, 'count': 7}}
Kenchenahalli {1: {'mean': 5646.853146853147, 'std': 646.8531468531469, 'count': 2}, 2: {'mean': 5274.4401769080805, 'std': 359.1996745553106, 'count': 7}, 3: {'mean': 5460.627817637033, 'std': 264.58222613843435, 'count': 3}}
Kengeri {1: {'mean': 4102.12346939793, 'std': 591.7443122845393, 'count': 9}}
Kengeri {1: {'mean': 4102.12346939793, 'std': 591.7443122845393, 'count': 9}, 2: {'mean': 4390.756355620633, 'std': 671.539951835691, 'count': 30}}
Kengeri {1: {'mean': 4102.12346939793, 'std': 591.7443122845393, 'count': 9}, 2: {'mean': 4390.756355620633, 'std': 671.539951835691, 'count': 30}, 3: {'mean': 4032.7478567837916, 'std': 657.8355516907933, 'count': 11}}
Kengeri {1: {'mean': 4102.12346939793, 'std': 591.7443122845393, 'count': 9}, 2: {'mean': 4390.756355620633, 'std': 671.539951835691, 'count': 30}, 3: {'mean': 4032.7478567837916, 'std': 657.8355516907933, 'count': 11}, 5: {'mean': 4000.0, 'std': 0.0, 'count': 1}}
Kengeri {1: {'mean': 4102.12346939793, 'std': 591.7443122845393, 'count': 9}, 2: {'mean': 4390.756355620633, 'std': 671.539951835691, 'count': 30}, 3: {'mean': 4032.7478567837916, 'std': 657.8355516907933, 'count': 11}, 5: {'mean': 4000.0, 'std': 0.0, 'count': 1}, 8: {'mean': 4333.333333333333, 'std': 0.0, 'count': 1}}
Kengeri Satellite Town {1: {'mean': 3416.085803355814, 'std': 180.47203987792676, 'count': 3}}
Kengeri Satellite Town {1: {'mean': 3416.085803355814, 'std': 180.47203987792676, 'count': 3}, 2: {'mean': 4161.885658225768, 'std': 587.9649928204554, 'count': 20}}
Kengeri Satellite Town {1: {'mean': 3416.085803355814, 'std': 180.47203987792676, 'count': 3}, 2: {'mean': 4161.885658225768, 'std': 587.9649928204554, 'count': 20}, 3: {'mean': 4294.409672655811, 'std': 599.879656057118, 'count': 3}}
Kereguddadahalli {1: {'mean': 3250.0, 'std': 0.0, 'count': 1}}
Kereguddadahalli {1: {'mean': 3250.0, 'std': 0.0, 'count': 1}, 2: {'mean': 3285.4634212085666, 'std': 199.6880849428014, 'count': 7}}
Kereguddadahalli {1: {'mean': 3250.0, 'std': 0.0, 'count': 1}, 2: {'mean': 3285.4634212085666, 'std': 199.6880849428014, 'count': 7}, 3: {'mean': 3203.254608294931, 'std': 173.2774907327058, 'count': 5}}
Kodichikkanahalli {1: {'mean': 4000.0, 'std': 0.0, 'count': 1}}
Kodichikkanahalli {1: {'mean': 4000.0, 'std': 0.0, 'count': 1}, 2: {'mean': 4464.71665687586, 'std': 329.5744118140759, 'count': 10}}
Kodichikkanahalli {1: {'mean': 4000.0, 'std': 0.0, 'count': 1}, 2: {'mean': 4464.71665687586, 'std': 329.5744118140759, 'count': 10}, 3: {'mean': 4663.38431038836, 'std': 430.5214561404485, 'count': 6}}
Kodichikkanahalli {1: {'mean': 4000.0, 'std': 0.0, 'count': 1}, 2: {'mean': 4464.71665687586, 'std': 329.5744118140759, 'count': 10}, 3: {'mean': 4663.38431038836, 'std': 430.5214561404485, 'count': 6}, 5: {'mean': 4753.086419753086, 'std': 174.5942669596414, 'count': 3}}
Kodigehaali {2: {'mean': 4568.752583055242, 'std': 504.85018578262014, 'count': 7}}
Kodigehaali {2: {'mean': 4568.752583055242, 'std': 504.85018578262014, 'count': 7}, 3: {'mean': 5932.628698743195, 'std': 1418.7220163805841, 'count': 4}}
Kodigehalli {1: {'mean': 8091.603053435115, 'std': 0.0, 'count': 1}}
Kodigehalli {1: {'mean': 8091.603053435115, 'std': 0.0, 'count': 1}, 2: {'mean': 5375.328083989501, 'std': 1663.9012335209106, 'count': 3}}
Kodigehalli {1: {'mean': 8091.603053435115, 'std': 0.0, 'count': 1}, 2: {'mean': 5375.328083989501, 'std': 1663.9012335209106, 'count': 3}, 3: {'mean': 10620.87912087912, 'std': 2379.120879120879, 'count': 2}}
Kodihalli {2: {'mean': 10067.114093959732, 'std': 0.0, 'count': 1}}
Kodihalli {2: {'mean': 10067.114093959732, 'std': 0.0, 'count': 1}, 3: {'mean': 10018.319753621405, 'std': 1044.2283661863166, 'count': 5}}
Kodihalli {2: {'mean': 10067.114093959732, 'std': 0.0, 'count': 1}, 3: {'mean': 10018.319753621405, 'std': 1044.2283661863166, 'count': 5}, 4: {'mean': 10893.922389045523, 'std': 716.3686036821398, 'count': 3}}
Kogilu {1: {'mean': 5159.365079365079, 'std': 1065.8231736741996, 'count': 3}}
Kogilu {1: {'mean': 5159.365079365079, 'std': 1065.8231736741996, 'count': 3}, 2: {'mean': 4475.604638481574, 'std': 211.3056933959039, 'count': 12}}
Kogilu {1: {'mean': 5159.365079365079, 'std': 1065.8231736741996, 'count': 3}, 2: {'mean': 4475.604638481574, 'std': 211.3056933959039, 'count': 12}, 3: {'mean': 6530.65790795312, 'std': 1644.139418598545, 'count': 5}}
Kogilu {1: {'mean': 5159.365079365079, 'std': 1065.8231736741996, 'count': 3}, 2: {'mean': 4475.604638481574, 'std': 211.3056933959039, 'count': 12}, 3: {'mean': 6530.65790795312, 'std': 1644.139418598545, 'count': 5}, 7: {'mean': 3460.912052117264, 'std': 0.0, 'count': 1}}
Konanakunte {2: {'mean': 6561.085972850678, 'std': 0.0, 'count': 1}}
Konanakunte {2: {'mean': 6561.085972850678, 'std': 0.0, 'count': 1}, 3: {'mean': 7154.421202441103, 'std': 858.8014581243333, 'count': 3}}
Konanakunte {2: {'mean': 6561.085972850678, 'std': 0.0, 'count': 1}, 3: {'mean': 7154.421202441103, 'std': 858.8014581243333, 'count': 3}, 4: {'mean': 10420.226018864567, 'std': 335.8570408452007, 'count': 3}}
Koramangala {2: {'mean': 9519.730600403604, 'std': 1946.4988338411724, 'count': 23}}
Koramangala {2: {'mean': 9519.730600403604, 'std': 1946.4988338411724, 'count': 23}, 3: {'mean': 9691.757083813118, 'std': 2332.1057526607897, 'count': 26}}
Koramangala {2: {'mean': 9519.730600403604, 'std': 1946.4988338411724, 'count': 23}, 3: {'mean': 9691.757083813118, 'std': 2332.1057526607897, 'count': 26}, 4: {'mean': 12567.348894001134, 'std': 1286.9271971129865, 'count': 5}}
Kothannur {2: {'mean': 3872.5655216562704, 'std': 177.44245428443105, 'count': 6}}
Kothannur {2: {'mean': 3872.5655216562704, 'std': 177.44245428443105, 'count': 6}, 3: {'mean': 3738.798485722216, 'std': 263.03140319128806, 'count': 6}}
Kothanur {1: {'mean': 4892.344497607655, 'std': 107.65550239234472, 'count': 2}}
Kothanur {1: {'mean': 4892.344497607655, 'std': 107.65550239234472, 'count': 2}, 2: {'mean': 4854.565077877619, 'std': 214.79334119523998, 'count': 25}}
Kothanur {1: {'mean': 4892.344497607655, 'std': 107.65550239234472, 'count': 2}, 2: {'mean': 4854.565077877619, 'std': 214.79334119523998, 'count': 25}, 3: {'mean': 5472.538361819055, 'std': 749.1480375203159, 'count': 27}}
Kothanur {1: {'mean': 4892.344497607655, 'std': 107.65550239234472, 'count': 2}, 2: {'mean': 4854.565077877619, 'std': 214.79334119523998, 'count': 25}, 3: {'mean': 5472.538361819055, 'std': 749.1480375203159, 'count': 27}, 4: {'mean': 6622.099164733684, 'std': 140.61768325220237, 'count': 2}}
Kothanur {1: {'mean': 4892.344497607655, 'std': 107.65550239234472, 'count': 2}, 2: {'mean': 4854.565077877619, 'std': 214.79334119523998, 'count': 25}, 3: {'mean': 5472.538361819055, 'std': 749.1480375203159, 'count': 27}, 4: {'mean': 6622.099164733684, 'std': 140.61768325220237, 'count': 2}, 5: {'mean': 5729.166666666667, 'std': 0.0, 'count': 1}}
Kudlu {1: {'mean': 4583.333333333333, 'std': 0.0, 'count': 1}}
Kudlu {1: {'mean': 4583.333333333333, 'std': 0.0, 'count': 1}, 2: {'mean': 4381.624103221706, 'std': 292.010615730984, 'count': 19}}
Kudlu {1: {'mean': 4583.333333333333, 'std': 0.0, 'count': 1}, 2: {'mean': 4381.624103221706, 'std': 292.010615730984, 'count': 19}, 3: {'mean': 4520.12211215998, 'std': 361.70349731102834, 'count': 4}}
Kudlu {1: {'mean': 4583.333333333333, 'std': 0.0, 'count': 1}, 2: {'mean': 4381.624103221706, 'std': 292.010615730984, 'count': 19}, 3: {'mean': 4520.12211215998, 'std': 361.70349731102834, 'count': 4}, 4: {'mean': 5428.571428571428, 'std': 0.0, 'count': 1}}
Kudlu Gate {1: {'mean': 7396.870554765292, 'std': 0.0, 'count': 1}}
Kudlu Gate {1: {'mean': 7396.870554765292, 'std': 0.0, 'count': 1}, 2: {'mean': 5148.4513864375285, 'std': 1338.7834520110716, 'count': 15}}
Kudlu Gate {1: {'mean': 7396.870554765292, 'std': 0.0, 'count': 1}, 2: {'mean': 5148.4513864375285, 'std': 1338.7834520110716, 'count': 15}, 3: {'mean': 5180.933397123558, 'std': 956.0823188606547, 'count': 20}}
Kudlu Gate {1: {'mean': 7396.870554765292, 'std': 0.0, 'count': 1}, 2: {'mean': 5148.4513864375285, 'std': 1338.7834520110716, 'count': 15}, 3: {'mean': 5180.933397123558, 'std': 956.0823188606547, 'count': 20}, 4: {'mean': 5324.675324675325, 'std': 0.0, 'count': 1}}

Kumaraswami Layout {1: {'mean': 9176.470588235294, 'std': 0.0, 'count': 1}}
Kumaraswami Layout {1: {'mean': 9176.470588235294, 'std': 0.0, 'count': 1}, 2: {'mean': 5400.1387604070305, 'std': 402.12974684506605, 'count': 3}}
Kumaraswami Layout {1: {'mean': 9176.470588235294, 'std': 0.0, 'count': 1}, 2: {'mean': 5400.1387604070305, 'std': 402.12974684506605, 'count': 3}, 3: {'mean': 5822.598600508905, 'std': 555.2046988018691, 'count': 4}}
Kumaraswami Layout {1: {'mean': 9176.470588235294, 'std': 0.0, 'count': 1}, 2: {'mean': 5400.1387604070305, 'std': 402.12974684506605, 'count': 3}, 3: {'mean': 5822.598600508905, 'std': 555.2046988018691, 'count': 4}, 4: {'mean': 5719.897959183673, 'std': 1230.1020408163267, 'count': 2}}
Kumaraswami Layout {1: {'mean': 9176.470588235294, 'std': 0.0, 'count': 1}, 2: {'mean': 5400.1387604070305, 'std': 402.12974684506605, 'count': 3}, 3: {'mean': 5822.598600508905, 'std': 555.2046988018691, 'count': 4}, 4: {'mean': 5719.897959183673, 'std': 1230.1020408163267, 'count': 2}, 7: {'mean': 4857.750896057347, 'std': 247.93337659741678, 'count': 3}}
Kundalahalli {2: {'mean': 6698.43287978371, 'std': 1531.9654271563063, 'count': 17}}
Kundalahalli {2: {'mean': 6698.43287978371, 'std': 1531.9654271563063, 'count': 17}, 3: {'mean': 7331.054453361016, 'std': 1214.518355980384, 'count': 22}}
Kundalahalli {2: {'mean': 6698.43287978371, 'std': 1531.9654271563063, 'count': 17}, 3: {'mean': 7331.054453361016, 'std': 1214.518355980384, 'count': 22}, 4: {'mean': 8365.231318918251, 'std': 1028.8263996833173, 'count': 3}}
LB Shastri Nagar {1: {'mean': 4812.0300751879695, 'std': 0.0, 'count': 1}}
LB Shastri Nagar {1: {'mean': 4812.0300751879695, 'std': 0.0, 'count': 1}, 2: {'mean': 5047.7294422212935, 'std': 827.4528669677713, 'count': 7}}
LB Shastri Nagar {1: {'mean': 4812.0300751879695, 'std': 0.0, 'count': 1}, 2: {'mean': 5047.7294422212935, 'std': 827.4528669677713, 'count': 7}, 3: {'mean': 4888.392857142857, 'std': 825.8928571428573, 'count': 2}}
Laggere {1: {'mean': 9079.301075268817, 'std': 1337.3655913978491, 'count': 2}}
Laggere {1: {'mean': 9079.301075268817, 'std': 1337.3655913978491, 'count': 2}, 2: {'mean': 6250.0, 'std': 0.0, 'count': 1}}
Laggere {1: {'mean': 9079.301075268817, 'std': 1337.3655913978491, 'count': 2}, 2: {'mean': 6250.0, 'std': 0.0, 'count': 1}, 3: {'mean': 10833.333333333334, 'std': 0.0, 'count': 1}}
Laggere {1: {'mean': 9079.301075268817, 'std': 1337.3655913978491, 'count': 2}, 2: {'mean': 6250.0, 'std': 0.0, 'count': 1}, 3: {'mean': 10833.333333333334, 'std': 0.0, 'count': 1}, 5: {'mean': 4464.285714285715, 'std': 0.0, 'count': 1}}
Lakshminarayana Pura {2: {'mean': 6489.713291330107, 'std': 297.6789512592486, 'count': 22}}
Lakshminarayana Pura {2: {'mean': 6489.713291330107, 'std': 297.6789512592486, 'count': 22}, 3: {'mean': 6841.666666666666, 'std': 91.66666666666652, 'count': 2}}
Lingadheeranahalli {3: {'mean': 6502.821516842215, 'std': 338.4280109369237, 'count': 15}}
Lingadheeranahalli {3: {'mean': 6502.821516842215, 'std': 338.4280109369237, 'count': 15}, 4: {'mean': 6948.373789156925, 'std': 137.69782791285036, 'count': 3}}
Magadi Road {2: {'mean': 4852.21635737729, 'std': 485.0957216437849, 'count': 8}}
Magadi Road {2: {'mean': 4852.21635737729, 'std': 485.0957216437849, 'count': 8}, 3: {'mean': 4739.009734462758, 'std': 584.121088892974, 'count': 6}}
Magadi Road {2: {'mean': 4852.21635737729, 'std': 485.0957216437849, 'count': 8}, 3: {'mean': 4739.009734462758, 'std': 584.121088892974, 'count': 6}, 4: {'mean': 6200.0, 'std': 0.0, 'count': 1}}
Magadi Road {2: {'mean': 4852.21635737729, 'std': 485.0957216437849, 'count': 8}, 3: {'mean': 4739.009734462758, 'std': 584.121088892974, 'count': 6}, 4: {'mean': 6200.0, 'std': 0.0, 'count': 1}, 5: {'mean': 7200.0, 'std': 0.0, 'count': 1}}
Magadi Road {2: {'mean': 4852.21635737729, 'std': 485.0957216437849, 'count': 8}, 3: {'mean': 4739.009734462758, 'std': 584.121088892974, 'count': 6}, 4: {'mean': 6200.0, 'std': 0.0, 'count': 1}, 5: {'mean': 7200.0, 'std': 0.0, 'count': 1}, 6: {'mean': 3916.6666666666665, 'std': 0.0, 'count': 1}}
Mahadevpura {1: {'mean': 4794.520547945205, 'std': 0.0, 'count': 1}}
Mahadevpura {1: {'mean': 4794.520547945205, 'std': 0.0, 'count': 1}, 2: {'mean': 4655.718115723707, 'std': 376.41780517833274, 'count': 12}}
Mahadevpura {1: {'mean': 4794.520547945205, 'std': 0.0, 'count': 1}, 2: {'mean': 4655.718115723707, 'std': 376.41780517833274, 'count': 12}, 3: {'mean': 4870.419072507448, 'std': 464.96928202282703, 'count': 9}}
Mahalakshmi Layout {2: {'mean': 7239.819004524887, 'std': 0.0, 'count': 1}}
Mahalakshmi Layout {2: {'mean': 7239.819004524887, 'std': 0.0, 'count': 1}, 3: {'mean': 8581.201137171287, 'std': 585.46552949538, 'count': 2}}
Mahalakshmi Layout {2: {'mean': 7239.819004524887, 'std': 0.0, 'count': 1}, 3: {'mean': 8581.201137171287, 'std': 585.46552949538, 'count': 2}, 4: {'mean': 11682.539682539682, 'std': 1650.793650793651, 'count': 2}}
Mallasandra {2: {'mean': 4778.701173252796, 'std': 525.1161356942022, 'count': 8}}
Mallasandra {2: {'mean': 4778.701173252796, 'std': 525.1161356942022, 'count': 8}, 3: {'mean': 5557.259722141612, 'std': 756.1882822123313, 'count': 5}}
Malleshpalya {2: {'mean': 4450.0450218933265, 'std': 715.3637519675409, 'count': 10}}
Malleshpalya {2: {'mean': 4450.0450218933265, 'std': 715.3637519675409, 'count': 10}, 3: {'mean': 4425.035578878555, 'std': 860.0436344837372, 'count': 4}}
Malleshwaram {1: {'mean': 10574.590792191524, 'std': 2309.1199297340045, 'count': 5}}
Malleshwaram {1: {'mean': 10574.590792191524, 'std': 2309.1199297340045, 'count': 5}, 2: {'mean': 10448.283856388975, 'std': 2127.1295449855347, 'count': 11}}
Malleshwaram {1: {'mean': 10574.590792191524, 'std': 2309.1199297340045, 'count': 5}, 2: {'mean': 10448.283856388975, 'std': 2127.1295449855347, 'count': 11}, 3: {'mean': 12878.871444966011, 'std': 1697.9956830033234, 'count': 23}}
Malleshwaram {1: {'mean': 10574.590792191524, 'std': 2309.1199297340045, 'count': 5}, 2: {'mean': 10448.283856388975, 'std': 2127.1295449855347, 'count': 11}, 3: {'mean': 12878.871444966011, 'std': 1697.9956830033234, 'count': 23}, 4: {'mean': 11241.379310344826, 'std': 1668.290924746567, 'count': 3}}
Malleshwaram {1: {'mean': 10574.590792191524, 'std': 2309.1199297340045, 'count': 5}, 2: {'mean': 10448.283856388975, 'std': 2127.1295449855347, 'count': 11}, 3: {'mean': 12878.871444966011, 'std': 1697.9956830033234, 'count': 23}, 4: {'mean': 11241.379310344826, 'std': 1668.290924746567, 'count': 3}, 7: {'mean': 18333.333333333332, 'std': 0.0, 'count': 1}}
Marathahalli {1: {'mean': 6443.713889143229, 'std': 707.710000973837, 'count': 5}}
Marathahalli {1: {'mean': 6443.713889143229, 'std': 707.710000973837, 'count': 5}, 2: {'mean': 5343.012421942325, 'std': 805.7151229412378, 'count': 71}}
Marathahalli {1: {'mean': 6443.713889143229, 'std': 707.710000973837, 'count': 5}, 2: {'mean': 5343.012421942325, 'std': 805.7151229412378, 'count': 71}, 3: {'mean': 5765.145600020765, 'std': 889.5759940637467, 'count': 53}}
Marathahalli {1: {'mean': 6443.713889143229, 'std': 707.710000973837, 'count': 5}, 2: {'mean': 5343.012421942325, 'std': 805.7151229412378, 'count': 71}, 3: {'mean': 5765.145600020765, 'std': 889.5759940637467, 'count': 53}, 4: {'mean': 6160.540698577995, 'std': 807.182049168838, 'count': 20}}
Margondanahalli {2: {'mean': 5437.351523296367, 'std': 285.9823054456937, 'count': 14}}
Margondanahalli {2: {'mean': 5437.351523296367, 'std': 285.9823054456937, 'count': 14}, 3: {'mean': 5057.999244463333, 'std': 256.1953829260381, 'count': 3}}
Marsur {3: {'mean': 8750.0, 'std': 1250.0, 'count': 2}}
Marsur {3: {'mean': 8750.0, 'std': 1250.0, 'count': 2}, 4: {'mean': 8055.555555555556, 'std': 0.0, 'count': 1}}
Mico Layout {1: {'mean': 3687.5, 'std': 0.0, 'count': 1}}
Mico Layout {1: {'mean': 3687.5, 'std': 0.0, 'count': 1}, 2: {'mean': 3682.9249609262856, 'std': 423.6831720283269, 'count': 5}}
Mico Layout {1: {'mean': 3687.5, 'std': 0.0, 'count': 1}, 2: {'mean': 3682.9249609262856, 'std': 423.6831720283269, 'count': 5}, 3: {'mean': 3748.827506277767, 'std': 314.5094797917012, 'count': 3}}
Mico Layout {1: {'mean': 3687.5, 'std': 0.0, 'count': 1}, 2: {'mean': 3682.9249609262856, 'std': 423.6831720283269, 'count': 5}, 3: {'mean': 3748.827506277767, 'std': 314.5094797917012, 'count': 3}, 9: {'mean': 4200.0, 'std': 0.0, 'count': 1}}
Munnekollal {2: {'mean': 4633.305616995026, 'std': 352.4310127906283, 'count': 7}}
Munnekollal {2: {'mean': 4633.305616995026, 'std': 352.4310127906283, 'count': 7}, 3: {'mean': 4802.422395043424, 'std': 125.38772727852572, 'count': 6}}
Murugeshpalya {2: {'mean': 5931.085462733437, 'std': 1214.4226459894464, 'count': 4}}
Murugeshpalya {2: {'mean': 5931.085462733437, 'std': 1214.4226459894464, 'count': 4}, 3: {'mean': 4523.355531891741, 'std': 450.61538528825935, 'count': 7}}
Mysore Road {2: {'mean': 5045.13969490634, 'std': 676.0447047409738, 'count': 22}}
Mysore Road {2: {'mean': 5045.13969490634, 'std': 676.0447047409738, 'count': 22}, 3: {'mean': 5084.04096522042, 'std': 644.0777907893389, 'count': 13}}
NGR Layout {2: {'mean': 4489.826297505917, 'std': 29.998439759192205, 'count': 8}}
NRI Layout {2: {'mean': 5086.0370370370365, 'std': 800.8574434434588, 'count': 3}}
NRI Layout {2: {'mean': 5086.0370370370365, 'std': 800.8574434434588, 'count': 3}, 3: {'mean': 4229.419325502037, 'std': 445.2318722352784, 'count': 3}}
NRI Layout {2: {'mean': 5086.0370370370365, 'std': 800.8574434434588, 'count': 3}, 3: {'mean': 4229.419325502037, 'std': 445.2318722352784, 'count': 3}, 4: {'mean': 5348.837209302325, 'std': 0.0, 'count': 1}}
NRI Layout {2: {'mean': 5086.0370370370365, 'std': 800.8574434434588, 'count': 3}, 3: {'mean': 4229.419325502037, 'std': 445.2318722352784, 'count': 3}, 4: {'mean': 5348.837209302325, 'std': 0.0, 'count': 1}, 5: {'mean': 5200.0, 'std': 0.0, 'count': 1}}
Nagarbhavi {1: {'mean': 5457.622557871108, 'std': 1066.4073158513404, 'count': 3}}
Nagarbhavi {1: {'mean': 5457.622557871108, 'std': 1066.4073158513404, 'count': 3}, 2: {'mean': 6395.988878268282, 'std': 3229.6096758102262, 'count': 16}}
Nagarbhavi {1: {'mean': 5457.622557871108, 'std': 1066.4073158513404, 'count': 3}, 2: {'mean': 6395.988878268282, 'std': 3229.6096758102262, 'count': 16}, 3: {'mean': 5500.568824727776, 'std': 1968.8111694638117, 'count': 17}}
Nagarbhavi {1: {'mean': 5457.622557871108, 'std': 1066.4073158513404, 'count': 3}, 2: {'mean': 6395.988878268282, 'std': 3229.6096758102262, 'count': 16}, 3: {'mean': 5500.568824727776, 'std': 1968.8111694638117, 'count': 17}, 4: {'mean': 12000.0, 'std': 2000.0, 'count': 2}}
Nagarbhavi {1: {'mean': 5457.622557871108, 'std': 1066.4073158513404, 'count': 3}, 2: {'mean': 6395.988878268282, 'std': 3229.6096758102262, 'count': 16}, 3: {'mean': 5500.568824727776, 'std': 1968.8111694638117, 'count': 17}, 4: {'mean': 12000.0, 'std': 2000.0, 'count': 2}, 5: {'mean': 7200.0, 'std': 0.0, 'count': 1}}
Nagasandra {2: {'mean': 5482.312925170068, 'std': 584.353741496599, 'count': 2}}
Nagasandra {2: {'mean': 5482.312925170068, 'std': 584.353741496599, 'count': 2}, 3: {'mean': 5757.575757575758, 'std': 0.0, 'count': 1}}
Nagasandra {2: {'mean': 5482.312925170068, 'std': 584.353741496599, 'count': 2}, 3: {'mean': 5757.575757575758, 'std': 0.0, 'count': 1}, 4: {'mean': 6235.119047619048, 'std': 193.45238095238074, 'count': 2}}
Nagavara {1: {'mean': 3500.0, 'std': 0.0, 'count': 1}}
Nagavara {1: {'mean': 3500.0, 'std': 0.0, 'count': 1}, 2: {'mean': 4493.627819930604, 'std': 461.4406306632376, 'count': 6}}
Nagavara {1: {'mean': 3500.0, 'std': 0.0, 'count': 1}, 2: {'mean': 4493.627819930604, 'std': 461.4406306632376, 'count': 6}, 3: {'mean': 6307.806359887731, 'std': 1811.5738366229782, 'count': 3}}
Nagavara {1: {'mean': 3500.0, 'std': 0.0, 'count': 1}, 2: {'mean': 4493.627819930604, 'std': 461.4406306632376, 'count': 6}, 3: {'mean': 6307.806359887731, 'std': 1811.5738366229782, 'count': 3}, 4: {'mean': 5265.610902466384, 'std': 257.5980819535639, 'count': 2}}
Nagavarapalya {1: {'mean': 7854.609929078014, 'std': 262.38738629341753, 'count': 4}}
Nagavarapalya {1: {'mean': 7854.609929078014, 'std': 262.38738629341753, 'count': 4}, 2: {'mean': 7379.161208587787, 'std': 622.908546711891, 'count': 3}}
Nagavarapalya {1: {'mean': 7854.609929078014, 'std': 262.38738629341753, 'count': 4}, 2: {'mean': 7379.161208587787, 'std': 622.908546711891, 'count': 3}, 3: {'mean': 6153.846153846154, 'std': 0.0, 'count': 1}}
Narayanapura {2: {'mean': 6417.676818637855, 'std': 641.5678764128289, 'count': 4}}
Narayanapura {2: {'mean': 6417.676818637855, 'std': 641.5678764128289, 'count': 4}, 3: {'mean': 5624.607559361702, 'std': 176.28469731669043, 'count': 4}}
Neeladri Nagar {1: {'mean': 3750.8127802427566, 'std': 837.10794554603, 'count': 3}}
Neeladri Nagar {1: {'mean': 3750.8127802427566, 'std': 837.10794554603, 'count': 3}, 2: {'mean': 3601.3181568393316, 'std': 896.300794280481, 'count': 5}}
Neeladri Nagar {1: {'mean': 3750.8127802427566, 'std': 837.10794554603, 'count': 3}, 2: {'mean': 3601.3181568393316, 'std': 896.300794280481, 'count': 5}, 3: {'mean': 4446.286519616966, 'std': 851.8567154201359, 'count': 3}}
Neeladri Nagar {1: {'mean': 3750.8127802427566, 'std': 837.10794554603, 'count': 3}, 2: {'mean': 3601.3181568393316, 'std': 896.300794280481, 'count': 5}, 3: {'mean': 4446.286519616966, 'std': 851.8567154201359, 'count': 3}, 10: {'mean': 4000.0, 'std': 0.0, 'count': 1}}
Nehru Nagar {2: {'mean': 4397.856538497696, 'std': 147.59800695684862, 'count': 2}}
Nehru Nagar {2: {'mean': 4397.856538497696, 'std': 147.59800695684862, 'count': 2}, 3: {'mean': 5323.390108322737, 'std': 476.8505751937556, 'count': 5}}
Nehru Nagar {2: {'mean': 4397.856538497696, 'std': 147.59800695684862, 'count': 2}, 3: {'mean': 5323.390108322737, 'std': 476.8505751937556, 'count': 5}, 4: {'mean': 4994.3116788028365, 'std': 83.97863012649077, 'count': 2}}
OMBR Layout {2: {'mean': 6060.732226936822, 'std': 765.1028054888121, 'count': 8}}
OMBR Layout {2: {'mean': 6060.732226936822, 'std': 765.1028054888121, 'count': 8}, 3: {'mean': 6395.974418965156, 'std': 1354.455921644706, 'count': 4}}
OMBR Layout {2: {'mean': 6060.732226936822, 'std': 765.1028054888121, 'count': 8}, 3: {'mean': 6395.974418965156, 'std': 1354.455921644706, 'count': 4}, 4: {'mean': 8088.235294117647, 'std': 0.0, 'count': 1}}
Old Airport Road {2: {'mean': 6488.103629335819, 'std': 666.8103212209145, 'count': 8}}
Old Airport Road {2: {'mean': 6488.103629335819, 'std': 666.8103212209145, 'count': 8}, 3: {'mean': 7732.476289952065, 'std': 1345.392120110078, 'count': 3}}
Old Airport Road {2: {'mean': 6488.103629335819, 'std': 666.8103212209145, 'count': 8}, 3: {'mean': 7732.476289952065, 'std': 1345.392120110078, 'count': 3}, 4: {'mean': 7400.652269436281, 'std': 366.6527535174725, 'count': 19}}
Old Madras Road {2: {'mean': 5660.295741126656, 'std': 850.7558483817651, 'count': 17}}
Old Madras Road {2: {'mean': 5660.295741126656, 'std': 850.7558483817651, 'count': 17}, 3: {'mean': 5877.4699494233955, 'std': 658.1522060566687, 'count': 17}}
Old Madras Road {2: {'mean': 5660.295741126656, 'std': 850.7558483817651, 'count': 17}, 3: {'mean': 5877.4699494233955, 'std': 658.1522060566687, 'count': 17}, 4: {'mean': 5568.646870314652, 'std': 445.15305178998693, 'count': 10}}
Old Madras Road {2: {'mean': 5660.295741126656, 'std': 850.7558483817651, 'count': 17}, 3: {'mean': 5877.4699494233955, 'std': 658.1522060566687, 'count': 17}, 4: {'mean': 5568.646870314652, 'std': 445.15305178998693, 'count': 10}, 5: {'mean': 6125.232403718459, 'std': 408.1009296148736, 'count': 2}}

Padmanabhanagar {2: {'mean': 6353.3984086808305, 'std': 1620.4038971043078, 'count': 8}}
Padmanabhanagar {2: {'mean': 6353.3984086808305, 'std': 1620.4038971043078, 'count': 8}, 3: {'mean': 6103.133559343508, 'std': 1413.7555415488598, 'count': 11}}
Padmanabhanagar {2: {'mean': 6353.3984086808305, 'std': 1620.4038971043078, 'count': 8}, 3: {'mean': 6103.133559343508, 'std': 1413.7555415488598, 'count': 11}, 4: {'mean': 6176.470588235294, 'std': 0.0, 'count': 1}}
Pai Layout {2: {'mean': 4275.598787873179, 'std': 847.9319844868568, 'count': 11}}
Pai Layout {2: {'mean': 4275.598787873179, 'std': 847.9319844868568, 'count': 11}, 3: {'mean': 4565.193665374716, 'std': 692.5145408804893, 'count': 5}}
Pai Layout {2: {'mean': 4275.598787873179, 'std': 847.9319844868568, 'count': 11}, 3: {'mean': 4565.193665374716, 'std': 692.5145408804893, 'count': 5}, 6: {'mean': 4605.263157894737, 'std': 0.0, 'count': 1}}
Panathur {1: {'mean': 6051.437216338881, 'std': 0.0, 'count': 1}}
Panathur {1: {'mean': 6051.437216338881, 'std': 0.0, 'count': 1}, 2: {'mean': 6163.683079124272, 'std': 522.5629147973473, 'count': 24}}
Panathur {1: {'mean': 6051.437216338881, 'std': 0.0, 'count': 1}, 2: {'mean': 6163.683079124272, 'std': 522.5629147973473, 'count': 24}, 3: {'mean': 5824.381873424201, 'std': 756.1120640080887, 'count': 5}}
Parappana Agrahara {1: {'mean': 3750.0, 'std': 0.0, 'count': 1}}
Parappana Agrahara {1: {'mean': 3750.0, 'std': 0.0, 'count': 1}, 2: {'mean': 3894.570971024669, 'std': 52.57420919375578, 'count': 14}}
Pattandur Agrahara {2: {'mean': 4818.300127405684, 'std': 256.46926050536257, 'count': 6}}
Pattandur Agrahara {2: {'mean': 4818.300127405684, 'std': 256.46926050536257, 'count': 6}, 3: {'mean': 5161.290322580645, 'std': 0.0, 'count': 2}}
Poorna Pragna Layout {2: {'mean': 4413.125572360624, 'std': 495.68839972297116, 'count': 6}}
Poorna Pragna Layout {2: {'mean': 4413.125572360624, 'std': 495.68839972297116, 'count': 6}, 3: {'mean': 4049.309690274269, 'std': 111.94750610317409, 'count': 12}}
Prithvi Layout {2: {'mean': 6037.440123978585, 'std': 549.2881072143185, 'count': 6}}
Prithvi Layout {2: {'mean': 6037.440123978585, 'std': 549.2881072143185, 'count': 6}, 3: {'mean': 8026.0686177976095, 'std': 1550.1613565960947, 'count': 3}}
Prithvi Layout {2: {'mean': 6037.440123978585, 'std': 549.2881072143185, 'count': 6}, 3: {'mean': 8026.0686177976095, 'std': 1550.1613565960947, 'count': 3}, 4: {'mean': 7988.165680473373, 'std': 0.0, 'count': 1}}
R.T. Nagar {2: {'mean': 6166.0990284595455, 'std': 2401.6080179377695, 'count': 11}}
R.T. Nagar {2: {'mean': 6166.0990284595455, 'std': 2401.6080179377695, 'count': 11}, 3: {'mean': 7778.645543303137, 'std': 2826.244096724054, 'count': 9}}
R.T. Nagar {2: {'mean': 6166.0990284595455, 'std': 2401.6080179377695, 'count': 11}, 3: {'mean': 7778.645543303137, 'std': 2826.244096724054, 'count': 9}, 4: {'mean': 7888.88888888889, 'std': 3247.030932489435, 'count': 3}}
R.T. Nagar {2: {'mean': 6166.0990284595455, 'std': 2401.6080179377695, 'count': 11}, 3: {'mean': 7778.645543303137, 'std': 2826.244096724054, 'count': 9}, 4: {'mean': 7888.88888888889, 'std': 3247.030932489435, 'count': 3}, 9: {'mean': 4583.333333333333, 'std': 0.0, 'count': 1}}
Rachenahalli {1: {'mean': 5122.705314009661, 'std': 456.3742317223319, 'count': 3}}
Rachenahalli {1: {'mean': 5122.705314009661, 'std': 456.3742317223319, 'count': 3}, 2: {'mean': 5011.121340348212, 'std': 151.79484867635873, 'count': 21}}
Rachenahalli {1: {'mean': 5122.705314009661, 'std': 456.3742317223319, 'count': 3}, 2: {'mean': 5011.121340348212, 'std': 151.79484867635873, 'count': 21}, 3: {'mean': 4932.080211090551, 'std': 417.32880100292226, 'count': 15}}
Rachenahalli {1: {'mean': 5122.705314009661, 'std': 456.3742317223319, 'count': 3}, 2: {'mean': 5011.121340348212, 'std': 151.79484867635873, 'count': 21}, 3: {'mean': 4932.080211090551, 'std': 417.32880100292226, 'count': 15}, 4: {'mean': 6015.859994531036, 'std': 0.0, 'count': 1}}
Raja Rajeshwari Nagar {1: {'mean': 4339.6530666138515, 'std': 543.1788208229217, 'count': 5}}
Raja Rajeshwari Nagar {1: {'mean': 4339.6530666138515, 'std': 543.1788208229217, 'count': 5}, 2: {'mean': 4119.938962696688, 'std': 797.0186502026783, 'count': 100}}
Raja Rajeshwari Nagar {1: {'mean': 4339.6530666138515, 'std': 543.1788208229217, 'count': 5}, 2: {'mean': 4119.938962696688, 'std': 797.0186502026783, 'count': 100}, 3: {'mean': 4316.218711504208, 'std': 847.5993608049711, 'count': 54}}
Raja Rajeshwari Nagar {1: {'mean': 4339.6530666138515, 'std': 543.1788208229217, 'count': 5}, 2: {'mean': 4119.938962696688, 'std': 797.0186502026783, 'count': 100}, 3: {'mean': 4316.218711504208, 'std': 847.5993608049711, 'count': 54}, 6: {'mean': 5000.0, 'std': 0.0, 'count': 1}}
Raja Rajeshwari Nagar {1: {'mean': 4339.6530666138515, 'std': 543.1788208229217, 'count': 5}, 2: {'mean': 4119.938962696688, 'std': 797.0186502026783, 'count': 100}, 3: {'mean': 4316.218711504208, 'std': 847.5993608049711, 'count': 54}, 6: {'mean': 5000.0, 'std': 0.0, 'count': 1}, 8: {'mean': 4930.857487922706, 'std': 1211.8785162729496, 'count': 3}}
Raja Rajeshwari Nagar {1: {'mean': 4339.6530666138515, 'std': 543.1788208229217, 'count': 5}, 2: {'mean': 4119.938962696688, 'std': 797.0186502026783, 'count': 100}, 3: {'mean': 4316.218711504208, 'std': 847.5993608049711, 'count': 54}, 6: {'mean': 5000.0, 'std': 0.0, 'count': 1}, 8: {'mean': 4930.857487922706, 'std': 1211.8785162729496, 'count': 3}, 9: {'mean': 6666.666666666667, 'std': 0.0, 'count': 1}}
Rajaji Nagar {1: {'mean': 11363.636363636364, 'std': 0.0, 'count': 1}}
Rajaji Nagar {1: {'mean': 11363.636363636364, 'std': 0.0, 'count': 1}, 2: {'mean': 13550.152331961022, 'std': 2381.326440584, 'count': 14}}
Rajaji Nagar {1: {'mean': 11363.636363636364, 'std': 0.0, 'count': 1}, 2: {'mean': 13550.152331961022, 'std': 2381.326440584, 'count': 14}, 3: {'mean': 14106.804544911796, 'std': 2072.9910392276593, 'count': 38}}
Rajaji Nagar {1: {'mean': 11363.636363636364, 'std': 0.0, 'count': 1}, 2: {'mean': 13550.152331961022, 'std': 2381.326440584, 'count': 14}, 3: {'mean': 14106.804544911796, 'std': 2072.9910392276593, 'count': 38}, 4: {'mean': 14088.257966543091, 'std': 2880.37358890078, 'count': 13}}
Rajaji Nagar {1: {'mean': 11363.636363636364, 'std': 0.0, 'count': 1}, 2: {'mean': 13550.152331961022, 'std': 2381.326440584, 'count': 14}, 3: {'mean': 14106.804544911796, 'std': 2072.9910392276593, 'count': 38}, 4: {'mean': 14088.257966543091, 'std': 2880.37358890078, 'count': 13}, 5: {'mean': 13757.502632502632, 'std': 2306.3948735573995, 'count': 4}}
Rajaji Nagar {1: {'mean': 11363.636363636364, 'std': 0.0, 'count': 1}, 2: {'mean': 13550.152331961022, 'std': 2381.326440584, 'count': 14}, 3: {'mean': 14106.804544911796, 'std': 2072.9910392276593, 'count': 38}, 4: {'mean': 14088.257966543091, 'std': 2880.37358890078, 'count': 13}, 5: {'mean': 13757.502632502632, 'std': 2306.3948735573995, 'count': 4}, 6: {'mean': 18000.0, 'std': 0.0, 'count': 1}}
Rajiv Nagar {2: {'mean': 6830.924551419025, 'std': 533.7908722073457, 'count': 3}}
Rajiv Nagar {2: {'mean': 6830.924551419025, 'std': 533.7908722073457, 'count': 3}, 3: {'mean': 7396.449704142012, 'std': 0.0, 'count': 1}}
Rajiv Nagar {2: {'mean': 6830.924551419025, 'std': 533.7908722073457, 'count': 3}, 3: {'mean': 7396.449704142012, 'std': 0.0, 'count': 1}, 4: {'mean': 6315.890833058215, 'std': 707.5762737250174, 'count': 6}}
Ramagondanahalli {1: {'mean': 5555.555555555556, 'std': 0.0, 'count': 1}}
Ramagondanahalli {1: {'mean': 5555.555555555556, 'std': 0.0, 'count': 1}, 2: {'mean': 4606.370427585701, 'std': 1235.7180227997476, 'count': 22}}
Ramagondanahalli {1: {'mean': 5555.555555555556, 'std': 0.0, 'count': 1}, 2: {'mean': 4606.370427585701, 'std': 1235.7180227997476, 'count': 22}, 3: {'mean': 5708.567918939573, 'std': 1498.853091063744, 'count': 23}}
Ramagondanahalli {1: {'mean': 5555.555555555556, 'std': 0.0, 'count': 1}, 2: {'mean': 4606.370427585701, 'std': 1235.7180227997476, 'count': 22}, 3: {'mean': 5708.567918939573, 'std': 1498.853091063744, 'count': 23}, 4: {'mean': 6714.753447126966, 'std': 1179.0391614126816, 'count': 2}}
Ramamurthy Nagar {1: {'mean': 6956.790123456791, 'std': 336.85836171956186, 'count': 3}}
Ramamurthy Nagar {1: {'mean': 6956.790123456791, 'std': 336.85836171956186, 'count': 3}, 2: {'mean': 4839.4046288157915, 'std': 1129.149258888949, 'count': 31}}
Ramamurthy Nagar {1: {'mean': 6956.790123456791, 'std': 336.85836171956186, 'count': 3}, 2: {'mean': 4839.4046288157915, 'std': 1129.149258888949, 'count': 31}, 3: {'mean': 4632.116991709435, 'std': 792.226666356907, 'count': 12}}
Ramamurthy Nagar {1: {'mean': 6956.790123456791, 'std': 336.85836171956186, 'count': 3}, 2: {'mean': 4839.4046288157915, 'std': 1129.149258888949, 'count': 31}, 3: {'mean': 4632.116991709435, 'std': 792.226666356907, 'count': 12}, 4: {'mean': 6625.8963789827985, 'std': 894.8595331526992, 'count': 3}}
Ramamurthy Nagar {1: {'mean': 6956.790123456791, 'std': 336.85836171956186, 'count': 3}, 2: {'mean': 4839.4046288157915, 'std': 1129.149258888949, 'count': 31}, 3: {'mean': 4632.116991709435, 'std': 792.226666356907, 'count': 12}, 4: {'mean': 6625.8963789827985, 'std': 894.8595331526992, 'count': 3}, 5: {'mean': 4285.714285714285, 'std': 0.0, 'count': 1}}
Rayasandra {1: {'mean': 4541.075143242948, 'std': 72.99003685996877, 'count': 2}}
Rayasandra {1: {'mean': 4541.075143242948, 'std': 72.99003685996877, 'count': 2}, 2: {'mean': 4425.750666858969, 'std': 146.01251895301732, 'count': 3}}
Rayasandra {1: {'mean': 4541.075143242948, 'std': 72.99003685996877, 'count': 2}, 2: {'mean': 4425.750666858969, 'std': 146.01251895301732, 'count': 3}, 3: {'mean': 4423.733966062286, 'std': 267.25133087914065, 'count': 9}}
Rayasandra {1: {'mean': 4541.075143242948, 'std': 72.99003685996877, 'count': 2}, 2: {'mean': 4425.750666858969, 'std': 146.01251895301732, 'count': 3}, 3: {'mean': 4423.733966062286, 'std': 267.25133087914065, 'count': 9}, 4: {'mean': 4449.648711943794, 'std': 0.0, 'count': 1}}
Rayasandra {1: {'mean': 4541.075143242948, 'std': 72.99003685996877, 'count': 2}, 2: {'mean': 4425.750666858969, 'std': 146.01251895301732, 'count': 3}, 3: {'mean': 4423.733966062286, 'std': 267.25133087914065, 'count': 9}, 4: {'mean': 4449.648711943794, 'std': 0.0, 'count': 1}, 5: {'mean': 4027.777777777778, 'std': 0.0, 'count': 1}}
Sahakara Nagar {2: {'mean': 5176.637205930015, 'std': 925.9779110123278, 'count': 19}}
Sahakara Nagar {2: {'mean': 5176.637205930015, 'std': 925.9779110123278, 'count': 19}, 3: {'mean': 6966.244540905622, 'std': 1251.2106654813592, 'count': 10}}
Sahakara Nagar {2: {'mean': 5176.637205930015, 'std': 925.9779110123278, 'count': 19}, 3: {'mean': 6966.244540905622, 'std': 1251.2106654813592, 'count': 10}, 4: {'mean': 7445.229681978799, 'std': 554.7703180212015, 'count': 2}}
Sanjay nagar {2: {'mean': 6408.0027636555515, 'std': 1008.5806527993847, 'count': 9}}
Sanjay nagar {2: {'mean': 6408.0027636555515, 'std': 1008.5806527993847, 'count': 9}, 3: {'mean': 8195.88626739262, 'std': 2037.2976973824375, 'count': 5}}
Sanjay nagar {2: {'mean': 6408.0027636555515, 'std': 1008.5806527993847, 'count': 9}, 3: {'mean': 8195.88626739262, 'std': 2037.2976973824375, 'count': 5}, 5: {'mean': 7575.757575757576, 'std': 0.0, 'count': 1}}
Sarakki Nagar {3: {'mean': 11677.772648686641, 'std': 1164.2113099564785, 'count': 7}}
Sarakki Nagar {3: {'mean': 11677.772648686641, 'std': 1164.2113099564785, 'count': 7}, 4: {'mean': 11118.213921641485, 'std': 58.695321233468675, 'count': 3}}
Sarjapur {1: {'mean': 2874.133538039441, 'std': 174.43064872118748, 'count': 4}}
Sarjapur {1: {'mean': 2874.133538039441, 'std': 174.43064872118748, 'count': 4}, 2: {'mean': 3604.54588824458, 'std': 718.1819172813347, 'count': 33}}
Sarjapur {1: {'mean': 2874.133538039441, 'std': 174.43064872118748, 'count': 4}, 2: {'mean': 3604.54588824458, 'std': 718.1819172813347, 'count': 33}, 3: {'mean': 4675.963272449762, 'std': 1139.724491656155, 'count': 20}}
Sarjapur {1: {'mean': 2874.133538039441, 'std': 174.43064872118748, 'count': 4}, 2: {'mean': 3604.54588824458, 'std': 718.1819172813347, 'count': 33}, 3: {'mean': 4675.963272449762, 'std': 1139.724491656155, 'count': 20}, 4: {'mean': 4798.6758762009795, 'std': 982.6102032032919, 'count': 11}}
Sarjapur  Road {1: {'mean': 5133.293879111827, 'std': 1040.4585511011248, 'count': 9}}
Sarjapur  Road {1: {'mean': 5133.293879111827, 'std': 1040.4585511011248, 'count': 9}, 2: {'mean': 5376.764753392969, 'std': 940.2539293683719, 'count': 114}}
Sarjapur  Road {1: {'mean': 5133.293879111827, 'std': 1040.4585511011248, 'count': 9}, 2: {'mean': 5376.764753392969, 'std': 940.2539293683719, 'count': 114}, 3: {'mean': 6069.097454249021, 'std': 1210.6553782479018, 'count': 153}}

Sarjapur  Road {1: {'mean': 5133.293879111827, 'std': 1040.4585511011248, 'count': 9}, 2: {'mean': 5376.764753392969, 'std': 940.2539293683719, 'count': 114}, 3: {'mean': 6069.097454249021, 'std': 1210.6553782479018, 'count': 153}, 4: {'mean': 6515.374368146306, 'std': 1322.5099449631382, 'count': 26}}
Sarjapur  Road {1: {'mean': 5133.293879111827, 'std': 1040.4585511011248, 'count': 9}, 2: {'mean': 5376.764753392969, 'std': 940.2539293683719, 'count': 114}, 3: {'mean': 6069.097454249021, 'std': 1210.6553782479018, 'count': 153}, 4: {'mean': 6515.374368146306, 'std': 1322.5099449631382, 'count': 26}, 5: {'mean': 5797.897681160006, 'std': 1209.3915232816719, 'count': 4}}
Sarjapura - Attibele Road {1: {'mean': 3195.945945945946, 'std': 0.0, 'count': 1}}
Sarjapura - Attibele Road {1: {'mean': 3195.945945945946, 'std': 0.0, 'count': 1}, 2: {'mean': 2980.300110459942, 'std': 240.74806987622512, 'count': 6}}
Sarjapura - Attibele Road {1: {'mean': 3195.945945945946, 'std': 0.0, 'count': 1}, 2: {'mean': 2980.300110459942, 'std': 240.74806987622512, 'count': 6}, 3: {'mean': 3677.009046693256, 'std': 568.4897414332066, 'count': 7}}
Sector 2 HSR Layout {1: {'mean': 7556.675062972292, 'std': 0.0, 'count': 1}}
Sector 2 HSR Layout {1: {'mean': 7556.675062972292, 'std': 0.0, 'count': 1}, 2: {'mean': 6104.475872678937, 'std': 867.7629358050074, 'count': 4}}
Sector 2 HSR Layout {1: {'mean': 7556.675062972292, 'std': 0.0, 'count': 1}, 2: {'mean': 6104.475872678937, 'std': 867.7629358050074, 'count': 4}, 3: {'mean': 5840.870632537299, 'std': 558.3617721495737, 'count': 3}}
Sector 7 HSR Layout {2: {'mean': 8517.539849533492, 'std': 29.88399409911783, 'count': 4}}
Sector 7 HSR Layout {2: {'mean': 8517.539849533492, 'std': 29.88399409911783, 'count': 4}, 3: {'mean': 8621.066433566433, 'std': 944.6855296740544, 'count': 6}}
Sector 7 HSR Layout {2: {'mean': 8517.539849533492, 'std': 29.88399409911783, 'count': 4}, 3: {'mean': 8621.066433566433, 'std': 944.6855296740544, 'count': 6}, 4: {'mean': 9166.666666666666, 'std': 0.0, 'count': 1}}
Seegehalli {2: {'mean': 4329.211790848419, 'std': 1166.1042598803597, 'count': 8}}
Seegehalli {2: {'mean': 4329.211790848419, 'std': 1166.1042598803597, 'count': 8}, 3: {'mean': 5367.419714920858, 'std': 1586.8132900699522, 'count': 11}}
Seegehalli {2: {'mean': 4329.211790848419, 'std': 1166.1042598803597, 'count': 8}, 3: {'mean': 5367.419714920858, 'std': 1586.8132900699522, 'count': 11}, 4: {'mean': 5000.0, 'std': 0.0, 'count': 2}}
Shampura {2: {'mean': 4708.333333333334, 'std': 291.6666666666665, 'count': 2}}
Shampura {2: {'mean': 4708.333333333334, 'std': 291.6666666666665, 'count': 2}, 3: {'mean': 4899.966766367564, 'std': 364.7021331777603, 'count': 3}}
Shampura {2: {'mean': 4708.333333333334, 'std': 291.6666666666665, 'count': 2}, 3: {'mean': 4899.966766367564, 'std': 364.7021331777603, 'count': 3}, 4: {'mean': 5660.377358490566, 'std': 0.0, 'count': 1}}
Shivaji Nagar {1: {'mean': 8010.471204188481, 'std': 0.0, 'count': 1}}
Shivaji Nagar {1: {'mean': 8010.471204188481, 'std': 0.0, 'count': 1}, 2: {'mean': 8177.670428057425, 'std': 1680.2831248065638, 'count': 4}}
Shivaji Nagar {1: {'mean': 8010.471204188481, 'std': 0.0, 'count': 1}, 2: {'mean': 8177.670428057425, 'std': 1680.2831248065638, 'count': 4}, 3: {'mean': 6164.3835616438355, 'std': 0.0, 'count': 1}}
Singasandra {2: {'mean': 4612.819625700124, 'std': 506.83386852214045, 'count': 10}}
Singasandra {2: {'mean': 4612.819625700124, 'std': 506.83386852214045, 'count': 10}, 3: {'mean': 4522.865156428246, 'std': 498.5677172187002, 'count': 7}}
Singasandra {2: {'mean': 4612.819625700124, 'std': 506.83386852214045, 'count': 10}, 3: {'mean': 4522.865156428246, 'std': 498.5677172187002, 'count': 7}, 4: {'mean': 4451.853329012638, 'std': 613.081735922427, 'count': 2}}
Somasundara Palya {2: {'mean': 5360.675549919206, 'std': 593.8769277607065, 'count': 8}}
Somasundara Palya {2: {'mean': 5360.675549919206, 'std': 593.8769277607065, 'count': 8}, 3: {'mean': 4740.491215564561, 'std': 690.4875020957893, 'count': 7}}
Somasundara Palya {2: {'mean': 5360.675549919206, 'std': 593.8769277607065, 'count': 8}, 3: {'mean': 4740.491215564561, 'std': 690.4875020957893, 'count': 7}, 4: {'mean': 5833.333333333333, 'std': 0.0, 'count': 1}}
Sompura {2: {'mean': 3840.4959109430956, 'std': 224.1921863747153, 'count': 4}}
Sompura {2: {'mean': 3840.4959109430956, 'std': 224.1921863747153, 'count': 4}, 3: {'mean': 3466.687036151407, 'std': 123.29979549236428, 'count': 3}}
Sompura {2: {'mean': 3840.4959109430956, 'std': 224.1921863747153, 'count': 4}, 3: {'mean': 3466.687036151407, 'std': 123.29979549236428, 'count': 3}, 4: {'mean': 3953.4883720930234, 'std': 0.0, 'count': 1}}
Sonnenahalli {1: {'mean': 4998.3598840688865, 'std': 0.012776630869666405, 'count': 2}}
Sonnenahalli {1: {'mean': 4998.3598840688865, 'std': 0.012776630869666405, 'count': 2}, 2: {'mean': 4451.776042086879, 'std': 424.19435489209496, 'count': 6}}
Sonnenahalli {1: {'mean': 4998.3598840688865, 'std': 0.012776630869666405, 'count': 2}, 2: {'mean': 4451.776042086879, 'std': 424.19435489209496, 'count': 6}, 3: {'mean': 4706.376756380032, 'std': 441.79167132471156, 'count': 5}}
Subramanyapura {2: {'mean': 5320.002594928582, 'std': 564.6089957428896, 'count': 14}}
Subramanyapura {2: {'mean': 5320.002594928582, 'std': 564.6089957428896, 'count': 14}, 3: {'mean': 5419.591639044803, 'std': 543.0872192059437, 'count': 13}}
Sultan Palaya {2: {'mean': 5516.726902965547, 'std': 1253.3841087551375, 'count': 5}}
Sultan Palaya {2: {'mean': 5516.726902965547, 'std': 1253.3841087551375, 'count': 5}, 3: {'mean': 6296.180318134044, 'std': 1250.8447106368387, 'count': 3}}
Sultan Palaya {2: {'mean': 5516.726902965547, 'std': 1253.3841087551375, 'count': 5}, 3: {'mean': 6296.180318134044, 'std': 1250.8447106368387, 'count': 3}, 4: {'mean': 6500.0, 'std': 0.0, 'count': 1}}
TC Palaya {1: {'mean': 4074.074074074074, 'std': 0.0, 'count': 1}}
TC Palaya {1: {'mean': 4074.074074074074, 'std': 0.0, 'count': 1}, 2: {'mean': 5697.4094763372195, 'std': 619.4809937733468, 'count': 20}}
TC Palaya {1: {'mean': 4074.074074074074, 'std': 0.0, 'count': 1}, 2: {'mean': 5697.4094763372195, 'std': 619.4809937733468, 'count': 20}, 3: {'mean': 5441.915480148754, 'std': 526.2209882855493, 'count': 25}}
TC Palaya {1: {'mean': 4074.074074074074, 'std': 0.0, 'count': 1}, 2: {'mean': 5697.4094763372195, 'std': 619.4809937733468, 'count': 20}, 3: {'mean': 5441.915480148754, 'std': 526.2209882855493, 'count': 25}, 4: {'mean': 6291.666666666667, 'std': 0.0, 'count': 1}}
Talaghattapura {2: {'mean': 4580.285299806576, 'std': 455.35287836606403, 'count': 4}}
Talaghattapura {2: {'mean': 4580.285299806576, 'std': 455.35287836606403, 'count': 4}, 3: {'mean': 6525.339233648821, 'std': 694.1463657221601, 'count': 22}}
Thanisandra {1: {'mean': 5536.748748889186, 'std': 843.2326580247442, 'count': 24}}
Thanisandra {1: {'mean': 5536.748748889186, 'std': 843.2326580247442, 'count': 24}, 2: {'mean': 5577.18388838983, 'std': 859.6650172856573, 'count': 48}}
Thanisandra {1: {'mean': 5536.748748889186, 'std': 843.2326580247442, 'count': 24}, 2: {'mean': 5577.18388838983, 'std': 859.6650172856573, 'count': 48}, 3: {'mean': 5963.98561560378, 'std': 646.7048899935486, 'count': 74}}
Thanisandra {1: {'mean': 5536.748748889186, 'std': 843.2326580247442, 'count': 24}, 2: {'mean': 5577.18388838983, 'std': 859.6650172856573, 'count': 48}, 3: {'mean': 5963.98561560378, 'std': 646.7048899935486, 'count': 74}, 4: {'mean': 5809.062417390094, 'std': 821.0388724789285, 'count': 6}}
Thanisandra {1: {'mean': 5536.748748889186, 'std': 843.2326580247442, 'count': 24}, 2: {'mean': 5577.18388838983, 'std': 859.6650172856573, 'count': 48}, 3: {'mean': 5963.98561560378, 'std': 646.7048899935486, 'count': 74}, 4: {'mean': 5809.062417390094, 'std': 821.0388724789285, 'count': 6}, 6: {'mean': 4571.428571428572, 'std': 0.0, 'count': 1}}
Thigalarapalya {2: {'mean': 7367.662128690889, 'std': 250.42902893834392, 'count': 15}}
Thigalarapalya {2: {'mean': 7367.662128690889, 'std': 250.42902893834392, 'count': 15}, 3: {'mean': 7195.7132993768455, 'std': 312.0510818458644, 'count': 25}}
Thigalarapalya {2: {'mean': 7367.662128690889, 'std': 250.42902893834392, 'count': 15}, 3: {'mean': 7195.7132993768455, 'std': 312.0510818458644, 'count': 25}, 4: {'mean': 7478.280524334292, 'std': 267.3908548713968, 'count': 11}}
Thubarahalli {2: {'mean': 6177.47488087532, 'std': 550.0809877574003, 'count': 11}}
Thubarahalli {2: {'mean': 6177.47488087532, 'std': 550.0809877574003, 'count': 11}, 3: {'mean': 6182.810245310246, 'std': 353.87655581660107, 'count': 4}}
Thubarahalli {2: {'mean': 6177.47488087532, 'std': 550.0809877574003, 'count': 11}, 3: {'mean': 6182.810245310246, 'std': 353.87655581660107, 'count': 4}, 4: {'mean': 6289.473684210527, 'std': 0.0, 'count': 1}}
Thyagaraja Nagar {1: {'mean': 12500.0, 'std': 0.0, 'count': 1}}
Thyagaraja Nagar {1: {'mean': 12500.0, 'std': 0.0, 'count': 1}, 2: {'mean': 6538.461538461538, 'std': 0.0, 'count': 1}}
Thyagaraja Nagar {1: {'mean': 12500.0, 'std': 0.0, 'count': 1}, 2: {'mean': 6538.461538461538, 'std': 0.0, 'count': 1}, 3: {'mean': 7500.0, 'std': 0.0, 'count': 1}}
Thyagaraja Nagar {1: {'mean': 12500.0, 'std': 0.0, 'count': 1}, 2: {'mean': 6538.461538461538, 'std': 0.0, 'count': 1}, 3: {'mean': 7500.0, 'std': 0.0, 'count': 1}, 5: {'mean': 7250.0, 'std': 0.0, 'count': 1}}
Tindlu {2: {'mean': 5123.714149465223, 'std': 97.42574991353615, 'count': 3}}
Tindlu {2: {'mean': 5123.714149465223, 'std': 97.42574991353615, 'count': 3}, 3: {'mean': 5283.565257806863, 'std': 516.6873757479673, 'count': 4}}
Tindlu {2: {'mean': 5123.714149465223, 'std': 97.42574991353615, 'count': 3}, 3: {'mean': 5283.565257806863, 'std': 516.6873757479673, 'count': 4}, 7: {'mean': 5333.333333333333, 'std': 0.0, 'count': 1}}
Tumkur Road {2: {'mean': 6222.216116265259, 'std': 565.4013168608797, 'count': 8}}
Tumkur Road {2: {'mean': 6222.216116265259, 'std': 565.4013168608797, 'count': 8}, 3: {'mean': 6367.716187279277, 'std': 390.8691579620035, 'count': 14}}
Ulsoor {2: {'mean': 8730.998103368149, 'std': 2062.5115260500042, 'count': 5}}
Ulsoor {2: {'mean': 8730.998103368149, 'std': 2062.5115260500042, 'count': 5}, 3: {'mean': 9156.582905880583, 'std': 1457.6390839943092, 'count': 7}}
Ulsoor {2: {'mean': 8730.998103368149, 'std': 2062.5115260500042, 'count': 5}, 3: {'mean': 9156.582905880583, 'std': 1457.6390839943092, 'count': 7}, 4: {'mean': 6800.0, 'std': 0.0, 'count': 1}}
Uttarahalli {1: {'mean': 5446.293494704993, 'std': 0.0, 'count': 1}}
Uttarahalli {1: {'mean': 5446.293494704993, 'std': 0.0, 'count': 1}, 2: {'mean': 4055.878990945823, 'std': 443.82742078600614, 'count': 75}}
Uttarahalli {1: {'mean': 5446.293494704993, 'std': 0.0, 'count': 1}, 2: {'mean': 4055.878990945823, 'std': 443.82742078600614, 'count': 75}, 3: {'mean': 4083.5276962879593, 'std': 534.1705599671546, 'count': 89}}
Uttarahalli {1: {'mean': 5446.293494704993, 'std': 0.0, 'count': 1}, 2: {'mean': 4055.878990945823, 'std': 443.82742078600614, 'count': 75}, 3: {'mean': 4083.5276962879593, 'std': 534.1705599671546, 'count': 89}, 4: {'mean': 3333.3333333333335, 'std': 0.0, 'count': 1}}
Uttarahalli {1: {'mean': 5446.293494704993, 'std': 0.0, 'count': 1}, 2: {'mean': 4055.878990945823, 'std': 443.82742078600614, 'count': 75}, 3: {'mean': 4083.5276962879593, 'std': 534.1705599671546, 'count': 89}, 4: {'mean': 3333.3333333333335, 'std': 0.0, 'count': 1}, 6: {'mean': 3333.3333333333335, 'std': 0.0, 'count': 1}}
Varthur {2: {'mean': 4331.910572925388, 'std': 847.3795043583863, 'count': 32}}
Varthur {2: {'mean': 4331.910572925388, 'std': 847.3795043583863, 'count': 32}, 3: {'mean': 4836.478103600665, 'std': 892.2656889001147, 'count': 14}}
Varthur Road {2: {'mean': 3754.9654055540996, 'std': 648.3927903937736, 'count': 7}}
Varthur Road {2: {'mean': 3754.9654055540996, 'std': 648.3927903937736, 'count': 7}, 3: {'mean': 3800.411985861906, 'std': 850.7508048357686, 'count': 2}}
Vasanthapura {2: {'mean': 3558.48776757308, 'std': 145.0953916099316, 'count': 7}}
Vidyaranyapura {2: {'mean': 4639.399867778706, 'std': 870.5642061348253, 'count': 16}}
Vidyaranyapura {2: {'mean': 4639.399867778706, 'std': 870.5642061348253, 'count': 16}, 3: {'mean': 5418.695502028836, 'std': 956.0813080374586, 'count': 6}}
Vidyaranyapura {2: {'mean': 4639.399867778706, 'std': 870.5642061348253, 'count': 16}, 3: {'mean': 5418.695502028836, 'std': 956.0813080374586, 'count': 6}, 4: {'mean': 6562.5, 'std': 937.5, 'count': 2}}
Vijayanagar {1: {'mean': 7513.33715688642, 'std': 1470.1647292081748, 'count': 4}}
Vijayanagar {1: {'mean': 7513.33715688642, 'std': 1470.1647292081748, 'count': 4}, 2: {'mean': 5936.626849748775, 'std': 879.0177188541079, 'count': 11}}
Vijayanagar {1: {'mean': 7513.33715688642, 'std': 1470.1647292081748, 'count': 4}, 2: {'mean': 5936.626849748775, 'std': 879.0177188541079, 'count': 11}, 3: {'mean': 6585.510613483119, 'std': 860.4381230168186, 'count': 17}}
Vijayanagar {1: {'mean': 7513.33715688642, 'std': 1470.1647292081748, 'count': 4}, 2: {'mean': 5936.626849748775, 'std': 879.0177188541079, 'count': 11}, 3: {'mean': 6585.510613483119, 'std': 860.4381230168186, 'count': 17}, 4: {'mean': 12000.0, 'std': 0.0, 'count': 1}}
Vijayanagar {1: {'mean': 7513.33715688642, 'std': 1470.1647292081748, 'count': 4}, 2: {'mean': 5936.626849748775, 'std': 879.0177188541079, 'count': 11}, 3: {'mean': 6585.510613483119, 'std': 860.4381230168186, 'count': 17}, 4: {'mean': 12000.0, 'std': 0.0, 'count': 1}, 5: {'mean': 5208.333333333333, 'std': 0.0, 'count': 1}}
Vishveshwarya Layout {1: {'mean': 4000.0, 'std': 0.0, 'count': 1}}
Vishveshwarya Layout {1: {'mean': 4000.0, 'std': 0.0, 'count': 1}, 4: {'mean': 4125.0, 'std': 375.0, 'count': 2}}
Vishveshwarya Layout {1: {'mean': 4000.0, 'std': 0.0, 'count': 1}, 4: {'mean': 4125.0, 'std': 375.0, 'count': 2}, 6: {'mean': 4380.952380952381, 'std': 0.0, 'count': 1}}

Vishwapriya Layout {2: {'mean': 3916.9969520750556, 'std': 177.84130871379733, 'count': 4}}
Vittasandra {2: {'mean': 5265.466588027837, 'std': 172.6857542886576, 'count': 31}}
Vittasandra {2: {'mean': 5265.466588027837, 'std': 172.6857542886576, 'count': 31}, 3: {'mean': 5113.14174326139, 'std': 100.56430016629145, 'count': 7}}
Whitefield {1: {'mean': 5765.189888976461, 'std': 1080.9401060122182, 'count': 26}}
Whitefield {1: {'mean': 5765.189888976461, 'std': 1080.9401060122182, 'count': 26}, 2: {'mean': 4996.6795555450735, 'std': 1261.8095382276895, 'count': 232}}
Whitefield {1: {'mean': 5765.189888976461, 'std': 1080.9401060122182, 'count': 26}, 2: {'mean': 4996.6795555450735, 'std': 1261.8095382276895, 'count': 232}, 3: {'mean': 5530.481945905363, 'std': 1329.8231587008422, 'count': 165}}
Whitefield {1: {'mean': 5765.189888976461, 'std': 1080.9401060122182, 'count': 26}, 2: {'mean': 4996.6795555450735, 'std': 1261.8095382276895, 'count': 232}, 3: {'mean': 5530.481945905363, 'std': 1329.8231587008422, 'count': 165}, 4: {'mean': 6781.906232032232, 'std': 1157.6199849662542, 'count': 57}}
Whitefield {1: {'mean': 5765.189888976461, 'std': 1080.9401060122182, 'count': 26}, 2: {'mean': 4996.6795555450735, 'std': 1261.8095382276895, 'count': 232}, 3: {'mean': 5530.481945905363, 'std': 1329.8231587008422, 'count': 165}, 4: {'mean': 6781.906232032232, 'std': 1157.6199849662542, 'count': 57}, 5: {'mean': 7836.874286815605, 'std': 794.7110211453303, 'count': 4}}
Yelachenahalli {2: {'mean': 5157.852477694467, 'std': 706.3466043126809, 'count': 7}}
Yelachenahalli {2: {'mean': 5157.852477694467, 'std': 706.3466043126809, 'count': 7}, 3: {'mean': 5909.760492768157, 'std': 1348.1242403302067, 'count': 5}}
Yelahanka {1: {'mean': 5250.754432669085, 'std': 708.186432901746, 'count': 16}}
Yelahanka {1: {'mean': 5250.754432669085, 'std': 708.186432901746, 'count': 16}, 2: {'mean': 4885.500091507662, 'std': 834.273883093863, 'count': 78}}
Yelahanka {1: {'mean': 5250.754432669085, 'std': 708.186432901746, 'count': 16}, 2: {'mean': 4885.500091507662, 'std': 834.273883093863, 'count': 78}, 3: {'mean': 5121.284167853844, 'std': 819.858135054314, 'count': 65}}
Yelahanka {1: {'mean': 5250.754432669085, 'std': 708.186432901746, 'count': 16}, 2: {'mean': 4885.500091507662, 'std': 834.273883093863, 'count': 78}, 3: {'mean': 5121.284167853844, 'std': 819.858135054314, 'count': 65}, 4: {'mean': 5396.634458670808, 'std': 859.2313582889707, 'count': 9}}
Yelahanka {1: {'mean': 5250.754432669085, 'std': 708.186432901746, 'count': 16}, 2: {'mean': 4885.500091507662, 'std': 834.273883093863, 'count': 78}, 3: {'mean': 5121.284167853844, 'std': 819.858135054314, 'count': 65}, 4: {'mean': 5396.634458670808, 'std': 859.2313582889707, 'count': 9}, 5: {'mean': 5150.0, 'std': 350.0, 'count': 2}}
Yelahanka {1: {'mean': 5250.754432669085, 'std': 708.186432901746, 'count': 16}, 2: {'mean': 4885.500091507662, 'std': 834.273883093863, 'count': 78}, 3: {'mean': 5121.284167853844, 'std': 819.858135054314, 'count': 65}, 4: {'mean': 5396.634458670808, 'std': 859.2313582889707, 'count': 9}, 5: {'mean': 5150.0, 'std': 350.0, 'count': 2}, 6: {'mean': 5555.555555555556, 'std': 0.0, 'count': 1}}
Yelahanka New Town {1: {'mean': 3711.0711616859157, 'std': 705.7257959858678, 'count': 12}}
Yelahanka New Town {1: {'mean': 3711.0711616859157, 'std': 705.7257959858678, 'count': 12}, 2: {'mean': 5255.289619148657, 'std': 1329.2576472001515, 'count': 7}}
Yelahanka New Town {1: {'mean': 3711.0711616859157, 'std': 705.7257959858678, 'count': 12}, 2: {'mean': 5255.289619148657, 'std': 1329.2576472001515, 'count': 7}, 3: {'mean': 5244.8328585493755, 'std': 1308.1039897883682, 'count': 12}}
Yelahanka New Town {1: {'mean': 3711.0711616859157, 'std': 705.7257959858678, 'count': 12}, 2: {'mean': 5255.289619148657, 'std': 1329.2576472001515, 'count': 7}, 3: {'mean': 5244.8328585493755, 'std': 1308.1039897883682, 'count': 12}, 4: {'mean': 5202.863961813842, 'std': 0.0, 'count': 1}}
Yelenahalli {2: {'mean': 3878.617021276596, 'std': 155.17896357207565, 'count': 7}}
Yelenahalli {2: {'mean': 3878.617021276596, 'std': 155.17896357207565, 'count': 7}, 3: {'mean': 3918.9457070707067, 'std': 143.76151982471873, 'count': 3}}
Yeshwanthpur {1: {'mean': 5660.6482445723395, 'std': 397.8138955809522, 'count': 13}}
Yeshwanthpur {1: {'mean': 5660.6482445723395, 'std': 397.8138955809522, 'count': 13}, 2: {'mean': 6313.582176150229, 'std': 1092.0986164191115, 'count': 23}}
Yeshwanthpur {1: {'mean': 5660.6482445723395, 'std': 397.8138955809522, 'count': 13}, 2: {'mean': 6313.582176150229, 'std': 1092.0986164191115, 'count': 23}, 3: {'mean': 6136.843144871886, 'std': 999.1342919214298, 'count': 31}}
Yeshwanthpur {1: {'mean': 5660.6482445723395, 'std': 397.8138955809522, 'count': 13}, 2: {'mean': 6313.582176150229, 'std': 1092.0986164191115, 'count': 23}, 3: {'mean': 6136.843144871886, 'std': 999.1342919214298, 'count': 31}, 4: {'mean': 6388.888888888889, 'std': 277.7777777777778, 'count': 2}}
Yeshwanthpur {1: {'mean': 5660.6482445723395, 'std': 397.8138955809522, 'count': 13}, 2: {'mean': 6313.582176150229, 'std': 1092.0986164191115, 'count': 23}, 3: {'mean': 6136.843144871886, 'std': 999.1342919214298, 'count': 31}, 4: {'mean': 6388.888888888889, 'std': 277.7777777777778, 'count': 2}, 6: {'mean': 7400.0, 'std': 0.0, 'count': 1}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}, 5: {'mean': 7278.542458208993, 'std': 3393.972878604103, 'count': 42}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}, 5: {'mean': 7278.542458208993, 'std': 3393.972878604103, 'count': 42}, 6: {'mean': 6975.562368913401, 'std': 3043.3045406755605, 'count': 34}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}, 5: {'mean': 7278.542458208993, 'std': 3393.972878604103, 'count': 42}, 6: {'mean': 6975.562368913401, 'std': 3043.3045406755605, 'count': 34}, 7: {'mean': 4272.049254022647, 'std': 1900.0507646394972, 'count': 11}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}, 5: {'mean': 7278.542458208993, 'std': 3393.972878604103, 'count': 42}, 6: {'mean': 6975.562368913401, 'std': 3043.3045406755605, 'count': 34}, 7: {'mean': 4272.049254022647, 'std': 1900.0507646394972, 'count': 11}, 8: {'mean': 5384.347002204145, 'std': 1946.6298824910634, 'count': 7}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}, 5: {'mean': 7278.542458208993, 'std': 3393.972878604103, 'count': 42}, 6: {'mean': 6975.562368913401, 'std': 3043.3045406755605, 'count': 34}, 7: {'mean': 4272.049254022647, 'std': 1900.0507646394972, 'count': 11}, 8: {'mean': 5384.347002204145, 'std': 1946.6298824910634, 'count': 7}, 9: {'mean': 5530.842391304348, 'std': 3234.230886145459, 'count': 4}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}, 5: {'mean': 7278.542458208993, 'std': 3393.972878604103, 'count': 42}, 6: {'mean': 6975.562368913401, 'std': 3043.3045406755605, 'count': 34}, 7: {'mean': 4272.049254022647, 'std': 1900.0507646394972, 'count': 11}, 8: {'mean': 5384.347002204145, 'std': 1946.6298824910634, 'count': 7}, 9: {'mean': 5530.842391304348, 'std': 3234.230886145459, 'count': 4}, 10: {'mean': 9005.681818181818, 'std': 4630.681818181818, 'count': 2}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}, 5: {'mean': 7278.542458208993, 'std': 3393.972878604103, 'count': 42}, 6: {'mean': 6975.562368913401, 'std': 3043.3045406755605, 'count': 34}, 7: {'mean': 4272.049254022647, 'std': 1900.0507646394972, 'count': 11}, 8: {'mean': 5384.347002204145, 'std': 1946.6298824910634, 'count': 7}, 9: {'mean': 5530.842391304348, 'std': 3234.230886145459, 'count': 4}, 10: {'mean': 9005.681818181818, 'std': 4630.681818181818, 'count': 2}, 11: {'mean': 4850.0, 'std': 2350.0, 'count': 2}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}, 5: {'mean': 7278.542458208993, 'std': 3393.972878604103, 'count': 42}, 6: {'mean': 6975.562368913401, 'std': 3043.3045406755605, 'count': 34}, 7: {'mean': 4272.049254022647, 'std': 1900.0507646394972, 'count': 11}, 8: {'mean': 5384.347002204145, 'std': 1946.6298824910634, 'count': 7}, 9: {'mean': 5530.842391304348, 'std': 3234.230886145459, 'count': 4}, 10: {'mean': 9005.681818181818, 'std': 4630.681818181818, 'count': 2}, 11: {'mean': 4850.0, 'std': 2350.0, 'count': 2}, 13: {'mean': 5069.124423963133, 'std': 0.0, 'count': 1}}
other {1: {'mean': 5321.358826419816, 'std': 2357.7059009960285, 'count': 132}, 2: {'mean': 5288.580186585404, 'std': 1981.80781113825, 'count': 987}, 3: {'mean': 6303.178181413835, 'std': 2552.0634251169126, 'count': 858}, 4: {'mean': 8334.159251776742, 'std': 2892.9656869519777, 'count': 224}, 5: {'mean': 7278.542458208993, 'std': 3393.972878604103, 'count': 42}, 6: {'mean': 6975.562368913401, 'std': 3043.3045406755605, 'count': 34}, 7: {'mean': 4272.049254022647, 'std': 1900.0507646394972, 'count': 11}, 8: {'mean': 5384.347002204145, 'std': 1946.6298824910634, 'count': 7}, 9: {'mean': 5530.842391304348, 'std': 3234.230886145459, 'count': 4}, 10: {'mean': 9005.681818181818, 'std': 4630.681818181818, 'count': 2}, 11: {'mean': 4850.0, 'std': 2350.0, 'count': 2}, 13: {'mean': 5069.124423963133, 'std': 0.0, 'count': 1}, 16: {'mean': 5500.0, 'std': 0.0, 'count': 1}}

In [61]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
                
            }
          
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft < (stats['mean'])].index.values)
                
    return df.drop(exclude_indices, axis = 'index')

In [62]:
df = bhk_outlier_remover(df)

In [63]:
df

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10292,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10293,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10296,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10297,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10300,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [65]:
df.drop(columns=['size', 'price_per_sqft'],inplace=True)#price_per_sqft we use this col to remove outliers now we dont need this

In [66]:
df

                  location  total_sqft  bath  price  bhk
0      1st Block Jayanagar      2850.0   4.0  428.0    4
1      1st Block Jayanagar      1630.0   3.0  194.0    3
2      1st Block Jayanagar      1875.0   2.0  235.0    3
3      1st Block Jayanagar      1200.0   2.0  130.0    3
4      1st Block Jayanagar      1235.0   2.0  148.0    2
...                    ...         ...   ...    ...  ...
10292                other      1200.0   2.0   70.0    2
10293                other      1800.0   1.0  200.0    1
10296                other      1353.0   2.0  110.0    2
10297                other       812.0   1.0   26.0    1
10300                other      3600.0   5.0  400.0    4

[7360 rows x 5 columns]

In [67]:
df.to_csv('cleaned_data.csv')

### Cleaned Data

In [3]:
df = pd.read_csv("cleaned_data.csv")
df.head()

   Unnamed: 0             location  total_sqft  bath  price  bhk
0           0  1st Block Jayanagar      2850.0   4.0  428.0    4
1           1  1st Block Jayanagar      1630.0   3.0  194.0    3
2           2  1st Block Jayanagar      1875.0   2.0  235.0    3
3           3  1st Block Jayanagar      1200.0   2.0  130.0    3
4           4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [10]:
df.drop(columns=['Unnamed: 0'], axis = 1, inplace=True)

In [11]:
## split the data for train and test

x = df.drop(columns=['price'])
y = df['price']

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [13]:
x_train,x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state=0)

In [14]:
print(x_train.shape)
print(x_test.shape)

(5888, 4)
(1472, 4)

### Applying Linear Regressor

In [15]:
column_trans = make_column_transformer((OneHotEncoder(sparse=False), ['location']), remainder='passthrough')

In [16]:
scaler = StandardScaler()

In [17]:
lr = LinearRegression(normalize=True)

In [18]:
pipe = make_pipeline(column_trans, scaler,lr)

In [19]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression(normalize=True))])

In [20]:
y_pred_lr = pipe.predict(x_test)
r2_score(y_test, y_pred_lr)

0.8295405537662313

### Applying Lasso

In [21]:
lasso = Lasso()

In [23]:
pipe = make_pipeline(column_trans, scaler, lasso)

In [24]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [25]:
y_pred_lasso = pipe.predict(x_test)
r2_score(y_test, y_pred_lasso)

0.8199181874762704

### Applying ridge

In [26]:
ridge = Ridge()

In [27]:
pipe = make_pipeline(column_trans, scaler, ridge)

In [28]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [29]:
y_pred_ridge = pipe.predict(x_test)
r2_score(y_test, y_pred_ridge)

0.8296651410179636

In [31]:
print("No Regularization: ", r2_score(y_test, y_pred_lr))
print("Lasso: ", r2_score(y_test, y_pred_lasso))
print("Ridge: ",r2_score(y_test, y_pred_ridge) )

No Regularization:  0.8295405537662313
Lasso:  0.8199181874762704
Ridge:  0.8296651410179636

In [32]:
import pickle

In [33]:
pickle.dump(pipe, open('RidgeModel.pkl', 'wb'))